// @ts-check
/**
 * D — Options/Gamma "Flow" subview + EdStream contract-binding invariants (#10 preserved).
 * Proves fail-closed observation of ONE explicitly-selected option contract: only an accepted control
 * request begins microstructure polling; ACTIVE only when the canonical producer confirms the desired
 * contract on BOTH services; MOVED/PENDING/FAILED render honestly; no re-POST/oscillation; every
 * NATIVE/DERIVED tag is the backend's own classification; no trade side, tape pressure or delta
 * is shown (Schwab sends no aggressor).
 *
 * PAYLOAD CONTRACT — the /api/order-flow/options-microstructure stub is the committed fixture
 * tests/e2e/fixtures/options_microstructure_payload.json, GENERATED by the real route handler
 * (tests/test_options_order_flow_production_v1.py::write_flow_e2e_fixture) and held to the route's
 * keys and values by test_flow_e2e_fixture_is_the_route_contract. Only `streaming_plane` is
 * overlaid per test (producer-binding scenarios).
 */
const { test, expect } = require('@playwright/test');
const FIXTURE = require('./fixtures/options_microstructure_payload.json');
const { served } = require('./fixtures/served_chain');

const DESIRED = FIXTURE.contract;                          // 'SPY   260911C00100000'
const OTHER = 'SPY   260911P00100000';

// Presentation formatting only (mirrors ed-gamma-flow.js num()/int(): fixed decimals / rounding).
const fmt = (n, d) => Number(n).toFixed(d);
const rowV = (page, k) => page.locator('#flowBody .fl-row[data-k="' + k + '"] .v');
const rowTag = (page, k) => page.locator('#flowBody .fl-row[data-k="' + k + '"] .fl-tag');

function chain() {
  function ct(side, k, sym) { return { putCall: side, strikePrice: k, symbol: sym, openInterest: 10, totalVolume: 5, volatility: 12, delta: side === 'CALL' ? 0.5 : -0.5, gamma: 0.01, expirationDate: '2026-09-11' }; }
  return { ticker: 'SPY', spot: 100, expiry: '2026-09-11', status: 'ok', scope: { kind: 'complete_single_expiry' },
    contracts: [ct('CALL', 100, DESIRED), ct('PUT', 100, OTHER)] };
}
/** The real route payload with this test's producer-binding plane overlaid; `mutate` (optional)
 *  edits a deep copy for negative controls. Nothing else in the payload is invented here. */
function microFor(plane, mutate) {
  const d = JSON.parse(JSON.stringify(FIXTURE));
  d.streaming_plane = Object.assign({}, d.streaming_plane, plane);
  if (mutate) mutate(d);
  return d;
}

function makeContext() {
  return { post: { status: 200, ok: true, echo: DESIRED }, plane: { contract_match: true, subscription_state: 'SUBSCRIBED', streaming_healthy: true, streaming_staleness_ms: 300 }, mutate: null, posts: 0, microGets: 0, hangMicro: false, releaseMicro: null };
}

async function setup(page, ctx) {
  await page.addInitScript(() => { try { localStorage.setItem('ed_ticker', 'SPY'); } catch (e) {} });
  await page.route('**/api/**', (route, request) => {
    const url = request.url();
    // RC-UI-3 (2026-09-12): /api/streaming/active-option-contractS (plural) is a SEPARATE
    // endpoint driven by the heatmap's Strike Detail panel (which auto-populates to the
    // spot strike on load -- see ed-gamma.js's "default the shared selection" comment),
    // sharing this same page/shell. The singular-endpoint substring below would also match
    // it, double-counting ctx.posts for a request this test's contract-binding assertions
    // are not about; fulfilled separately here and excluded from the singular match.
    if (url.includes('/api/streaming/active-option-contracts')) {
      return route.fulfill({ status: 200, contentType: 'application/json',
        body: JSON.stringify({ ok: true, contracts: [] }) });
    }
    if (url.includes('/api/streaming/active-option-contract') && request.method() === 'POST') {
      ctx.posts++;
      let contract = ''; try { contract = JSON.parse(request.postData() || '{}').contract || ''; } catch (e) {}
      const p = ctx.post;
      return route.fulfill({ status: p.status, contentType: 'application/json',
        body: JSON.stringify({ ok: p.ok, contract: (p.echo != null ? p.echo : contract), command_generation: 1, superseded: p.status === 409 }) });
    }
    if (url.includes('/api/order-flow/options-microstructure')) {
      ctx.microGets++;
      const body = JSON.stringify(microFor(ctx.plane, ctx.mutate));
      if (ctx.hangMicro) {
        return new Promise((resolve) => {
          ctx.releaseMicro = () => resolve(route.fulfill({ status: 200, contentType: 'application/json', body }));
        });
      }
      return route.fulfill({ status: 200, contentType: 'application/json', body });
    }
    let body = { available: false };
    if (url.includes('/api/chain')) body = served(chain());
    else if (url.includes('/api/options/gamma-surface')) body = { ticker: 'SPY', available: true, spot: 100, source: 'terrain_live_cache', live: true, stale: false, expirations: [{ expiry: '2026-09-11', dte: 2 }], strikes: [100], cells: [{ strike: 100, gex: [1] }] };
    else if (url.includes('/api/terrain/strikes')) body = { spot: 100, today_source: 'terrain_live_cache', today_age_sec: 5, levels_stale: false, today: { all: [[100, 1, 1]] } };
    else if (url.includes('/api/terrain')) body = { spot: 100, gamma_flip: 99.5, levels_stale: false };
    else if (url.includes('/api/expiries')) body = { expiries: ['2026-09-11'] };    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
  });
}

async function selectCallAndOpenFlow(page) {
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.locator('#subnav .tab', { hasText: 'Chain' }).click();
  await expect(page.locator('#chainBody table.chn-bodytbl')).toBeVisible();
  await page.locator('#chainBody tr[data-csym="' + DESIRED + '"] td.chn-call').first().click();
  await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
  await expect(page.locator('#flowBody')).toBeVisible();
}

test.describe('D — Gamma Flow subview (EdStream contract binding)', () => {
  test('no contract selected -> fail closed (Select a Call or Put contract), no subscription request', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await page.goto('/', { waitUntil: 'domcontentloaded' });
    await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(ctx.posts).toBe(0); expect(ctx.microGets).toBe(0);
  });

  test('ACTIVE only when producer confirms desired on both services; served values, the served Call/Put, no trade side', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);   // plane.contract_match:true
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(page.locator('#flowBody .fl-sym')).toHaveText(DESIRED);
    await expect(page.locator('#flowBody .fl-meta')).toContainText('Call');                   // d.put_call, Schwab's CONTRACT_TYPE
    await expect(rowV(page, 'top_of_book.bid')).toHaveText(fmt(FIXTURE.top_of_book.bid, 2));   // native bid served (1.20)
    await expect(rowV(page, 'top_of_book.bid_size')).toHaveText(String(Math.round(FIXTURE.top_of_book.bid_size)));
    await expect(rowV(page, 'mid')).toHaveText(fmt(FIXTURE.mid, 2));
    await expect(rowV(page, 'microprice')).toHaveText(fmt(FIXTURE.microprice, 2));
    await expect(rowV(page, 'top_book_pressure')).toHaveText(fmt(FIXTURE.top_book_pressure, 3));
    await expect(rowV(page, 'depth.1.imbalance')).toHaveText(fmt(FIXTURE.depth['1'].imbalance, 3));
    await expect(rowV(page, 'ages.book_age_sec')).toHaveText(Math.round(FIXTURE.ages.book_age_sec) + 's');
    await expect(page.locator('#flowBody .fl-tag.native').first()).toBeVisible();
    await expect(page.locator('#flowBody .fl-tag.derived').first()).toBeVisible();
    // no trade side, tape pressure or delta: nothing served, nothing shown
    expect(FIXTURE.flow).toBeUndefined();
    await expect(page.locator('#flowBody .fl-tag.proxy')).toHaveCount(0);
    await expect(page.locator('#flowBody .fl-row[data-k^="flow."]')).toHaveCount(0);
    await expect(page.locator('#flowBody .fl-foot')).toContainText('Schwab sends no trade side');
    expect(ctx.posts).toBe(1);
  });

  test('a contract whose type Schwab has not streamed shows no Call/Put, never one read off the symbol', async ({ page }) => {
    const ctx = makeContext(); ctx.mutate = (d) => { d.put_call = null; };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(page.locator('#flowBody .fl-meta')).not.toContainText('Call');
    await expect(page.locator('#flowBody .fl-meta')).toContainText('—');
  });

  test('every classification tag equals the backend classification EXACTLY', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    // d.classification (engine) -> book rows: exact keys, and the wildcard depth keys.
    const bc = FIXTURE.classification;
    expect(bc.top_book_pressure).toBe('DERIVED');
    for (const k of ['top_of_book.bid', 'top_of_book.ask', 'top_of_book.bid_size', 'top_of_book.ask_size', 'mid', 'microprice', 'spread_pts', 'top_book_pressure', 'ages.book_age_sec', 'ages.quote_age_sec']) {
      expect(typeof bc[k]).toBe('string');
      await expect(rowTag(page, k)).toHaveText(bc[k]);
    }
    for (const n of ['1', '3', '5']) await expect(rowTag(page, 'depth.' + n + '.imbalance')).toHaveText(bc['depth.*.imbalance']);
    await expect(rowTag(page, 'depth.5.bid_total')).toHaveText(bc['depth.*.bid_total']);
    await expect(rowTag(page, 'depth.5.ask_total')).toHaveText(bc['depth.*.ask_total']);
    // Feed health is not a classified metric: no tag is manufactured for it.
    await expect(rowTag(page, 'streaming_plane.streaming_healthy')).toHaveCount(0);
    // No section-level (hardcoded) tag exists anywhere: every tag sits in a row — and the panel header
    // carries no static NATIVE/PROXY chips either (a classification claim nothing served).
    await expect(page.locator('#flowBody .fl-sec-h .fl-tag')).toHaveCount(0);
    await expect(page.locator('[data-sub-pane="flow"] .panel-h .prov')).toHaveCount(0);
  });

  test('changing a classification in the payload changes the tag; a missing classification reads UNKNOWN', async ({ page }) => {
    const ctx = makeContext();
    ctx.mutate = (d) => {
      d.classification.top_book_pressure = 'PROXY';              // was DERIVED
      d.classification.mid = 'PROXY';                            // was DERIVED
      d.classification['top_of_book.bid'] = 'DERIVED-HEURISTIC (test)';   // an arbitrary backend string, verbatim
      delete d.classification.microprice;                        // served value, no classification
    };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(rowTag(page, 'top_book_pressure')).toHaveText('PROXY');
    await expect(rowTag(page, 'mid')).toHaveText('PROXY');
    await expect(rowTag(page, 'top_of_book.bid')).toHaveText('DERIVED-HEURISTIC (test)');
    await expect(rowTag(page, 'microprice')).toHaveText('UNKNOWN');
    await expect(rowTag(page, 'microprice')).toHaveClass(/unknown/);
    await expect(rowV(page, 'microprice')).toHaveText(fmt(FIXTURE.microprice, 2));   // value still served
    await expect(rowTag(page, 'spread_pts')).toHaveText(FIXTURE.classification.spread_pts);   // untouched rows unchanged
  });

  test('producer partial (L1 desired, book other) = NOT ACTIVE (PENDING, dimmed)', async ({ page }) => {
    const ctx = makeContext();
    ctx.plane = { contract_match: false, subscription_state: 'PENDING', producer_l1_contract: DESIRED, producer_book_contract: OTHER };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('PENDING');
    await expect(page.locator('#flowBody .fl-sec.fl-dim').first()).toBeVisible();  // data recedes when not active
  });

  test('slot taken by another contract = MOVED; desired shown, no re-POST', async ({ page }) => {
    const ctx = makeContext();
    ctx.plane = { contract_match: false, subscription_state: 'MOVED', producer_l1_contract: OTHER, producer_book_contract: OTHER };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('MOVED');
    await expect(page.locator('#flowBody .fl-sym')).toHaveText(DESIRED);           // still shows OUR desired, not the other
    const postsAfter = ctx.posts;
    await page.waitForTimeout(500);
    expect(ctx.posts).toBe(postsAfter);                                            // no automatic re-POST
  });

  test('failed control request (500) = FAILED, no microstructure polling', async ({ page }) => {
    const ctx = makeContext(); ctx.post = { status: 500, ok: false, echo: DESIRED };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('FAILED');
    expect(ctx.microGets).toBe(0);                                                 // never polled a non-accepted contract
  });

  test('ticker change clears local intent (no POST); Flow -> Gamma -> Flow makes no new request', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    const posts1 = ctx.posts;
    // Flow -> Gamma -> Flow: no new subscription request
    await page.locator('#subnav .tab', { hasText: 'Gamma' }).click();
    await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
    expect(ctx.posts).toBe(posts1);
    // ticker change clears the desired locally, no POST
    await page.locator('#symInput').fill('QQQ'); await page.locator('#symInput').press('Enter');
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(await page.evaluate(() => window.EdStream.getDesired())).toBeNull();
    expect(ctx.posts).toBe(posts1);                                                // clearing never POSTs
  });

  test('a delayed microstructure response for the OLD contract cannot resurrect after a ticker switch clears intent (state-authority review)', async ({ page }) => {
    // Independent-review finding (2026-09-12, state-authority review), REPRODUCED
    // ("Flow resurrection"): ed-gamma-flow.js's `_gen` guard used to be bumped only on
    // the branch that dispatches a NEW fetch (requires desired!=null && ctl==='accepted'),
    // never on the branch that CLEARS it. A ticker switch calls EdStream.clearDesired()
    // then load(): desired is now null, so load() returned before ever bumping `_gen`.
    // An in-flight microstructure fetch dispatched for the OLD contract (still holding
    // the OLD `g === _gen`) stayed "current" through the switch -- its late response
    // would render the OLD contract's ACTIVE badge/bid under the NEW ticker's label
    // (already updated by set()). Reproduced here: select SPY's contract (microstructure
    // fetch hangs), switch ticker to QQQ (clears desired, Flow shows NONE), THEN release
    // the hung SPY response -- it must not repaint anything.
    const ctx = makeContext(); await setup(page, ctx);
    ctx.hangMicro = true;
    await selectCallAndOpenFlow(page);
    await expect.poll(() => ctx.microGets).toBeGreaterThanOrEqual(1);   // the SPY fetch is in flight, hanging
    expect(await page.evaluate(() => window.EdStream.getDesired())).toBe(DESIRED);

    // Switch ticker BEFORE the hung SPY response resolves.
    await page.locator('#symInput').fill('QQQ'); await page.locator('#symInput').press('Enter');
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(await page.evaluate(() => window.EdStream.getDesired())).toBeNull();

    // NOW release the stale SPY response -- it must not resurrect ACTIVE/the old contract.
    // A plain `expect(locator).toContainText(...)` auto-retries for up to its timeout, so
    // a TRANSIENT bad paint that a LATER, unrelated event happens to correct before the
    // retry window elapses would silently pass -- this reproduced exactly that way on
    // first draft (a momentary resurrection, corrected moments later by an unrelated
    // poll tick, still read back as a pass). A single, non-retrying snapshot of the DOM
    // taken immediately after the release is the only way to catch the transient itself.
    ctx.hangMicro = false;
    if (ctx.releaseMicro) ctx.releaseMicro();
    await page.waitForTimeout(150);   // let any (incorrect) late-render attempt land
    const html = await page.locator('#flowBody').innerHTML();
    expect(html).not.toContain('ACTIVE');
    expect(html).not.toContain(DESIRED);
    expect(html).toContain('Select a Call or Put contract');
    expect(html).toContain('>NONE<');
  });
});
