// @ts-check
/**
 * D — Options/Gamma "Flow" subview: ONE explicitly-selected option contract (a Chain click), named to
 * the console so the daemon streams it (POST /api/flow-contract), observed through the route. The
 * badge is the served subscription state: ACTIVE while the daemon streams the contract, NOT STREAMED
 * otherwise; every NATIVE/DERIVED/PROXY tag is the backend's own classification;
 * native_aggressor_available=false => no signed flow.
 *
 * PAYLOAD CONTRACT — the /api/order-flow/options-microstructure stub is the committed fixture
 * tests/e2e/fixtures/options_microstructure_payload.json, GENERATED by the real route's producer from
 * real Schwab messages (tests/test_options_order_flow_production_v1.py::write_flow_e2e_fixture) and
 * held to the route by test_flow_e2e_fixture_is_the_route_contract. Only `streaming_plane` is
 * overlaid per test. The flow fields live under `flow` — never flattened — so a green run here proves
 * compatibility with the REAL API shape.
 */
const { test, expect } = require('@playwright/test');
const FIXTURE = require('./fixtures/options_microstructure_payload.json');
const { served } = require('./fixtures/served_chain');
const { routeWatchlist } = require('./fixtures/watchlist');

const SELECTED = FIXTURE.contract;                         // 'TSLA  260831C00367500'
const OTHER = 'TSLA  260831P00367500';

// Presentation formatting only (mirrors ed-gamma-flow.js num()/int(): fixed decimals / rounding).
const fmt = (n, d) => Number(n).toFixed(d);
const rowV = (page, k) => page.locator('#flowBody .fl-row[data-k="' + k + '"] .v');
const rowTag = (page, k) => page.locator('#flowBody .fl-row[data-k="' + k + '"] .fl-tag');

function chain() {
  function ct(side, k, sym) { return { putCall: side, strikePrice: k, symbol: sym, openInterest: 10, totalVolume: 5, volatility: 12, delta: side === 'CALL' ? 0.5 : -0.5, gamma: 0.01, expirationDate: '2026-08-31' }; }
  return { ticker: 'TSLA', spot: 367, expiry: '2026-08-31', status: 'ok', scope: { kind: 'complete_single_expiry' },
    contracts: [ct('CALL', 367.5, SELECTED), ct('PUT', 367.5, OTHER)] };
}
/** The real route payload with this test's plane overlaid; `mutate` (optional) edits a deep copy
 *  for negative controls. Nothing else in the payload is invented here. */
function microFor(plane, mutate) {
  const d = JSON.parse(JSON.stringify(FIXTURE));
  d.streaming_plane = Object.assign({}, d.streaming_plane, plane);
  if (mutate) mutate(d);
  return d;
}

function makeContext() {
  return { plane: {}, mutate: null, posts: [], microGets: 0, hangMicro: false, releaseMicro: null };
}

async function setup(page, ctx) {
  await page.addInitScript(() => { try { localStorage.setItem('ed_ticker', 'TSLA'); } catch (e) {} });
  // FALSIFIER (re-runnable from the tree): ED_FLOW_JS_OVERRIDE=<file> serves that file as
  // ed-gamma-flow.js, so the negative controls can be shown to FAIL against a consumer that reads
  // the old flattened shape / hardcodes tags.
  if (process.env.ED_FLOW_JS_OVERRIDE) {
    const body = require('node:fs').readFileSync(process.env.ED_FLOW_JS_OVERRIDE, 'utf8');
    await page.route('**/static/js/ed-gamma-flow.js', (route) => route.fulfill({ status: 200, contentType: 'application/javascript', body }));
  }
  await page.route('**/api/**', (route, request) => {
    const url = request.url();
    if (url.includes('/api/flow-contract') && request.method() === 'POST') {
      const contract = JSON.parse(request.postData()).contract;
      ctx.posts.push(contract);
      return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ ok: true, contract: contract }) });
    }
    if (url.includes('/api/order-flow/options-microstructure')) {
      ctx.microGets++;
      const body = JSON.stringify(microFor(ctx.plane, ctx.mutate));
      if (ctx.hangMicro) {
        return new Promise((resolve) => {
          ctx.releaseMicro = () => resolve(route.fulfill({ status: 200, contentType: 'application/json', body }));
        });
      }
      return route.fulfill({ status: 200, contentType: 'application/json', body });
    }
    let body = { available: false };
    if (url.includes('/api/chain')) body = served(chain());
    else if (url.includes('/api/options/gamma-surface')) body = { ticker: 'TSLA', available: true, spot: 367, source: 'terrain_live_cache', live: true, stale: false, expirations: [{ expiry: '2026-08-31', dte: 2 }], strikes: [367.5], cells: [{ strike: 367.5, gex: [1] }],
      view: { centre: 367.5, scope: 'auto', coverage: null, max_abs: { gex: 1 }, missing_expiry: null } };
    else if (url.includes('/api/terrain/strikes')) body = { spot: 367, today_source: 'terrain_live_cache', today_age_sec: 5, levels_stale: false, today: { all: [[367.5, 1, 1]] },
      views: { all: { centre: 367.5, note: null, max_abs: 1 } } };
    else if (url.includes('/api/terrain')) body = { spot: 367, gamma_flip: 366, levels_stale: false };
    else if (url.includes('/api/expiries')) body = { expiries: ['2026-08-31'] };
    return route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(body) });
  });
  await routeWatchlist(page, ['TSLA']);
}

async function selectCallAndOpenFlow(page) {
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.locator('#subnav .tab', { hasText: 'Chain' }).click();
  await expect(page.locator('#chainBody table.chn-bodytbl')).toBeVisible();
  await page.locator('#chainBody tr[data-csym="' + SELECTED + '"] td.chn-call').first().click();
  await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
  await expect(page.locator('#flowBody')).toBeVisible();
}

test.describe('D — Gamma Flow subview', () => {
  test('no contract selected -> fail closed (Select a Call or Put contract), nothing named, nothing read', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await page.goto('/', { waitUntil: 'domcontentloaded' });
    await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(ctx.posts).toEqual([]); expect(ctx.microGets).toBe(0);
  });

  test('the selected contract is named once to stream; ACTIVE while the daemon streams it; classifications + no signed flow', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);   // the fixture's plane: SUBSCRIBED
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(page.locator('#flowBody .fl-sym')).toHaveText(SELECTED);
    await expect(rowV(page, 'top_of_book.bid')).toHaveText(fmt(FIXTURE.top_of_book.bid, 2));   // Schwab's bid as sent
    await expect(page.locator('#flowBody .fl-tag.native').first()).toBeVisible();  // NATIVE/DERIVED/PROXY labels
    await expect(page.locator('#flowBody .fl-tag.derived').first()).toBeVisible();
    await expect(page.locator('#flowBody .fl-tag.proxy').first()).toBeVisible();
    await expect(page.locator('#flowBody .fl-foot')).toContainText('NOT PROVEN');  // no signed buys/sells
    expect(FIXTURE.flow.native_aggressor_available).toBe(false);                  // the backend's own truth...
    await expect(page.locator('#flowBody .fl-foot')).toContainText('native_aggressor_available=false');   // ...rendered verbatim
    await expect(page.locator('#flowBody .fl-foot')).toContainText('tape_classification=' + FIXTURE.flow.tape_classification);
    expect(ctx.posts).toEqual([SELECTED]);
    await page.setViewportSize({ width: 1672, height: 941 });
    await page.screenshot({ path: 'test-results/gamma-flow-1672x941.png', fullPage: false });
  });

  test('NEGATIVE CONTROL: nested-only payload (no flattened flow fields) renders the real flow values', async ({ page }) => {
    // The fixture is the real route response: flow fields exist ONLY under `flow`.
    for (const k of ['tape_pressure_30s', 'tape_pressure_2m', 'tape_pressure_5m', 'cum_delta_proxy', 'cum_delta_slope', 'top_book_pressure', 'native_aggressor_available']) {
      expect(FIXTURE[k]).toBeUndefined();
      expect(FIXTURE.flow[k]).not.toBeUndefined();
    }
    // Ages are the payload's own `ages` block, not a streaming_plane field.
    expect(FIXTURE.streaming_plane.book_age_sec).toBeUndefined();
    expect(FIXTURE.ages.book_age_sec).not.toBeNull();
    const ctx = makeContext(); await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(rowV(page, 'flow.tape_pressure_30s')).toHaveText(fmt(FIXTURE.flow.tape_pressure_30s, 3));
    await expect(rowV(page, 'flow.tape_pressure_2m')).toHaveText(fmt(FIXTURE.flow.tape_pressure_2m, 3));
    await expect(rowV(page, 'flow.tape_pressure_5m')).toHaveText(fmt(FIXTURE.flow.tape_pressure_5m, 3));
    // the cumulative delta with the window of prints it sums, served beside it
    await expect(rowV(page, 'flow.cum_delta_proxy')).toHaveText(fmt(FIXTURE.flow.cum_delta_proxy, 1) + ' · ' + FIXTURE.flow.cum_delta_window);
    await expect(rowV(page, 'flow.cum_delta_slope')).toHaveText(fmt(FIXTURE.flow.cum_delta_slope, 3));
    await expect(rowV(page, 'flow.top_book_pressure')).toHaveText(fmt(FIXTURE.flow.top_book_pressure, 3));
    await expect(rowV(page, 'mid')).toHaveText(fmt(FIXTURE.mid, 2));
    await expect(rowV(page, 'microprice')).toHaveText(fmt(FIXTURE.microprice, 2));
    await expect(rowV(page, 'depth.1.imbalance')).toHaveText(fmt(FIXTURE.depth['1'].imbalance, 3));
    await expect(rowV(page, 'top_of_book.bid_size')).toHaveText(String(Math.round(FIXTURE.top_of_book.bid_size)));
    await expect(rowV(page, 'ages.book_age_sec')).toHaveText(Math.round(FIXTURE.ages.book_age_sec) + 's');
    // No flow row fell back to the absent-value placeholder.
    for (const k of ['flow.tape_pressure_30s', 'flow.tape_pressure_2m', 'flow.tape_pressure_5m', 'flow.cum_delta_proxy', 'flow.cum_delta_slope', 'flow.top_book_pressure']) {
      await expect(rowV(page, k)).not.toHaveText('—');
    }
  });

  test('NEGATIVE CONTROL: decoys at the OLD flattened locations are ignored — only the nested contract is read', async ({ page }) => {
    const ctx = makeContext();
    ctx.mutate = (d) => {
      d.tape_pressure_30s = 0.999; d.tape_pressure_2m = 0.999; d.tape_pressure_5m = 0.999;
      d.cum_delta_proxy = -9999; d.cum_delta_slope = -9.999; d.top_book_pressure = 0.888;
      d.native_aggressor_available = true;          // a flattened decoy claiming native aggressor
      d.streaming_plane.book_age_sec = 1;           // an age at the old (wrong) location
    };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(rowV(page, 'flow.tape_pressure_30s')).toHaveText(fmt(FIXTURE.flow.tape_pressure_30s, 3));
    await expect(rowV(page, 'flow.cum_delta_proxy')).toHaveText(fmt(FIXTURE.flow.cum_delta_proxy, 1) + ' · ' + FIXTURE.flow.cum_delta_window);
    await expect(rowV(page, 'flow.top_book_pressure')).toHaveText(fmt(FIXTURE.flow.top_book_pressure, 3));
    await expect(rowV(page, 'ages.book_age_sec')).toHaveText(Math.round(FIXTURE.ages.book_age_sec) + 's');
    await expect(page.locator('#flowBody')).not.toContainText('0.999');
    await expect(page.locator('#flowBody')).not.toContainText('0.888');
    await expect(page.locator('#flowBody')).not.toContainText('-9999');
    await expect(page.locator('#flowBody .fl-foot')).toContainText('native_aggressor_available=false');
  });

  test('every classification tag equals the backend classification EXACTLY (flow + book)', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    // flow.classification -> rows data-k="flow.<key>"
    const fc = FIXTURE.flow.classification;
    expect(Object.keys(fc).length).toBeGreaterThan(0);
    expect(fc.tape_pressure_30s).toBe('PROXY'); expect(fc.top_book_pressure).toBe('DERIVED');   // the backend's actual verdicts
    for (const [k, v] of Object.entries(fc)) await expect(rowTag(page, 'flow.' + k)).toHaveText(v);
    // d.classification (engine) -> book rows: exact keys, and the wildcard depth keys.
    const bc = FIXTURE.classification;
    for (const k of ['top_of_book.bid', 'top_of_book.ask', 'top_of_book.bid_size', 'top_of_book.ask_size', 'mid', 'microprice', 'spread_pts', 'ages.book_age_sec', 'ages.quote_age_sec']) {
      expect(typeof bc[k]).toBe('string');
      await expect(rowTag(page, k)).toHaveText(bc[k]);
    }
    for (const n of ['1', '3', '5']) await expect(rowTag(page, 'depth.' + n + '.imbalance')).toHaveText(bc['depth.*.imbalance']);
    await expect(rowTag(page, 'depth.5.bid_total')).toHaveText(bc['depth.*.bid_total']);
    await expect(rowTag(page, 'depth.5.ask_total')).toHaveText(bc['depth.*.ask_total']);
    // Feed health is not a classified metric: no tag is manufactured for it.
    await expect(rowTag(page, 'streaming_plane.feed_health.replay')).toHaveCount(0);
    // No section-level (hardcoded) tag exists anywhere: every tag sits in a row — and the panel header
    // carries no static NATIVE/PROXY chips either (a classification claim nothing served).
    await expect(page.locator('#flowBody .fl-sec-h .fl-tag')).toHaveCount(0);
    await expect(page.locator('[data-sub-pane="flow"] .panel-h .prov')).toHaveCount(0);
  });

  test('changing a classification in the payload changes the tag; a missing classification reads UNKNOWN', async ({ page }) => {
    const ctx = makeContext();
    ctx.mutate = (d) => {
      d.flow.classification.tape_pressure_30s = 'NATIVE';        // was PROXY
      d.flow.classification.top_book_pressure = 'PROXY';         // was DERIVED
      d.classification.mid = 'PROXY';                            // was DERIVED
      d.classification['top_of_book.bid'] = 'DERIVED-HEURISTIC (test)';   // an arbitrary backend string, verbatim
      delete d.flow.classification.cum_delta_slope;              // served value, no classification
      delete d.flow.native_aggressor_available;                  // absent => not fabricated as false
    };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await expect(rowTag(page, 'flow.tape_pressure_30s')).toHaveText('NATIVE');
    await expect(rowTag(page, 'flow.top_book_pressure')).toHaveText('PROXY');
    await expect(rowTag(page, 'mid')).toHaveText('PROXY');
    await expect(rowTag(page, 'top_of_book.bid')).toHaveText('DERIVED-HEURISTIC (test)');
    await expect(rowTag(page, 'flow.cum_delta_slope')).toHaveText('UNKNOWN');
    await expect(rowTag(page, 'flow.cum_delta_slope')).toHaveClass(/unknown/);
    await expect(rowV(page, 'flow.cum_delta_slope')).toHaveText(fmt(FIXTURE.flow.cum_delta_slope, 3));   // value still served
    await expect(rowTag(page, 'flow.tape_pressure_2m')).toHaveText(FIXTURE.flow.classification.tape_pressure_2m);   // untouched rows unchanged
    await expect(page.locator('#flowBody .fl-foot')).toContainText('native_aggressor_available=—');
    await expect(page.locator('#flowBody .fl-foot')).not.toContainText('native_aggressor_available=false');
  });

  test('a contract the daemon does not stream reads NOT STREAMED and its data recedes', async ({ page }) => {
    const ctx = makeContext();
    ctx.plane = { subscription_state: 'NOT STREAMED' };
    await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('NOT STREAMED');
    await expect(page.locator('#flowBody .fl-sec.fl-dim').first()).toBeVisible();
  });

  test('a ticker change releases the selection once; Flow -> Gamma -> Flow names nothing again', async ({ page }) => {
    const ctx = makeContext(); await setup(page, ctx);
    await selectCallAndOpenFlow(page);
    await expect(page.locator('#flowBody .fl-badge')).toHaveText('ACTIVE');
    await page.locator('#subnav .tab', { hasText: 'Gamma' }).click();
    await page.locator('#subnav .tab', { hasText: 'Flow' }).click();
    expect(ctx.posts).toEqual([SELECTED]);
    await page.locator('#symInput').fill('QQQ'); await page.locator('#symInput').press('Enter');
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(await page.evaluate(() => window.EdFlow.selected())).toBeNull();
    await expect.poll(() => ctx.posts).toEqual([SELECTED, null]);
  });

  test('a delayed microstructure response for the OLD contract cannot resurrect after a ticker switch clears the selection (state-authority review)', async ({ page }) => {
    // REPRODUCED 2026-09-12 ("Flow resurrection"): an in-flight microstructure fetch for the OLD
    // contract, released after a ticker switch cleared the selection, repainted the OLD
    // contract's ACTIVE badge under the NEW ticker. A response is current only while its contract
    // is still the selected one.
    const ctx = makeContext(); await setup(page, ctx);
    ctx.hangMicro = true;
    await selectCallAndOpenFlow(page);
    await expect.poll(() => ctx.microGets).toBeGreaterThanOrEqual(1);   // the fetch is in flight, hanging
    expect(await page.evaluate(() => window.EdFlow.selected())).toBe(SELECTED);

    await page.locator('#symInput').fill('QQQ'); await page.locator('#symInput').press('Enter');
    await expect(page.locator('#flowBody')).toContainText('Select a Call or Put contract');
    expect(await page.evaluate(() => window.EdFlow.selected())).toBeNull();

    // A single, non-retrying snapshot right after the release catches a transient bad paint.
    ctx.hangMicro = false;
    if (ctx.releaseMicro) ctx.releaseMicro();
    await page.waitForTimeout(150);   // let any (incorrect) late-render attempt land
    const html = await page.locator('#flowBody').innerHTML();
    expect(html).not.toContain('ACTIVE');
    expect(html).not.toContain(SELECTED);
    expect(html).toContain('Select a Call or Put contract');
    expect(html).toContain('>NONE<');
  });
});
