"""Options/order-flow production path: default contract, live payload, history, stream lock.

# universal-scope-ok: fixtures use banked CDE/SPY contract rows as vendor-symbol
# examples of the enrolled-universe capture path, not a SPY-only product claim.
"""
from __future__ import annotations

import json
import sqlite3
import time
from stream_spine import STREAM_SCHEMA_SQL


def _cde_fixture_chain():
    from pathlib import Path

    fx_path = Path(__file__).resolve().parent / "fixtures" / "real_cde_complete_chain_half_dollar.json"
    return json.loads(fx_path.read_text(encoding="utf-8"))


def test_pick_atm_call_uses_vendor_symbol_not_constructed():
    from app.options.contracts.default import pick_atm_call_symbol

    fx = _cde_fixture_chain()
    contracts = fx["chain"]
    calls = [c for c in contracts if str(c.get("putCall") or "").upper() == "CALL"]
    assert calls, "real CDE fixture must include CALL rows"
    spot = float(calls[0]["strikePrice"]) + 0.1
    picked = pick_atm_call_symbol(contracts, spot)
    assert picked is not None
    row = next(c for c in contracts if c.get("symbol") == picked)
    assert str(row.get("putCall") or "").upper() == "CALL"
    assert picked == row["symbol"]
    assert pick_atm_call_symbol(contracts, None) is None


def test_default_contract_from_banked_chain(tmp_path, monkeypatch):
    from app.options.contracts.default import default_option_contract, pick_atm_call_symbol
    from calibration.complete_chain_capture import persist_complete_chain_capture

    fx = _cde_fixture_chain()
    monkeypatch.setattr("app.options.contracts.default._expiry_cutoff_et", lambda: fx["expiry"])
    db = tmp_path / "ed.db"
    persist_complete_chain_capture(
        db,
        ticker=fx["ticker"],
        expiry=fx["expiry"],
        contracts=fx["chain"],
        spot=16.1,
        completeness_basis=fx["completeness_basis"],
    )
    assert default_option_contract(fx["ticker"], chain_db_path=db) == pick_atm_call_symbol(fx["chain"], 16.1)


def test_live_payload_one_compute_includes_proxy_flow():
    import app.options.order_flow.state as ofls
    from app.options.order_flow.live_payload import options_live_payload

    contract = "CDE   260904C00013000"
    ofls.clear_all_live_state()
    ofls.push_book(contract, {
        "key": contract,
        "BOOK_TIME": int(time.time() * 1000),
        "BIDS": [{"BID_PRICE": 1.10, "TOTAL_VOLUME": 40}],
        "ASKS": [{"ASK_PRICE": 1.20, "TOTAL_VOLUME": 50}],
    })
    ofls.push_level_one(contract, {
        "key": contract,
        "BID_PRICE": 1.10, "ASK_PRICE": 1.20,
        "LAST_PRICE": 1.15, "LAST_SIZE": 3,
        "TRADE_TIME_MILLIS": int(time.time() * 1000),
    })
    payload = options_live_payload(contract)
    assert payload["status"] == "ok"
    assert "flow" in payload
    assert payload["flow"]["classification"]["cum_delta_proxy"] == "PROXY"
    assert payload["flow"]["native_aggressor_available"] is False
    ofls.clear_all_live_state()


def test_history_hydrates_from_stream_capture_only(tmp_path, monkeypatch):
    from app.options.order_flow.history import hydrate_option_content
    db = tmp_path / "stream_capture.db"
    con = sqlite3.connect(str(db))
    con.executescript(STREAM_SCHEMA_SQL)
    now = time.time()
    sym = "CDE   260904C00013000"
    con.execute(
        "INSERT INTO stream_options_quotes_raw(ts_recv,symbol,native_json,src) VALUES(?,?,?,?)",
        (now, sym, json.dumps({"LAST_PRICE": 1.15, "LAST_SIZE": 2, "TRADE_TIME_MILLIS": 1}), "test"),
    )
    con.execute(
        "INSERT INTO stream_book_raw(ts_recv,symbol,service,native_json,src) VALUES(?,?,?,?,?)",
        (now, sym, "OPTIONS_BOOK",
         json.dumps({"BIDS": [{"BID_PRICE": 1.1, "TOTAL_VOLUME": 1}],
                     "ASKS": [{"ASK_PRICE": 1.2, "TOTAL_VOLUME": 1}],
                     "BOOK_TIME": int(now * 1000)}), "test"),
    )
    con.commit()
    con.close()
    monkeypatch.setenv("STREAM_CAPTURE_DB_PATH", str(db.resolve()))
    # resolve_stream_db_path reads env fresh
    items = hydrate_option_content(sym, since_ts=now - 10, db_path=db)
    assert items
    assert any("LAST_PRICE" in x for x in items)
    assert any("BIDS" in x for x in items)
    from app.options.order_flow.live_payload import options_live_payload
    payload = options_live_payload(sym, content=items)
    assert payload["status"] == "ok"


# ─────────────────────────────────────────────────────────────────────────────
# E2E FIXTURE CONTRACT — the Playwright Flow spec (tests/e2e/console-gamma-flow.spec.js)
# stubs /api/order-flow/options-microstructure with tests/e2e/fixtures/
# options_microstructure_payload.json. That file is GENERATED by the real route handler
# below, never hand-written, and this test proves its key structure still equals what the
# route serves today. A stub that drifts from the route is a false proof: the earlier
# Flow spec stubbed the flow fields FLATTENED at the top level while the route nests them
# under `flow`, and its green run proved nothing about the real API.
#
# Regenerate (from the repo root, project .venv):
#   python -c "from tests.test_options_order_flow_production_v1 import write_flow_e2e_fixture; write_flow_e2e_fixture()"
# ─────────────────────────────────────────────────────────────────────────────

_FLOW_E2E_CONTRACT = "SPY   260911C00100000"
_FLOW_E2E_FIXTURE = "options_microstructure_payload.json"
_FLOW_E2E_BOOK_TIME_MS = 1789000000000


def _flow_e2e_fixture_path():
    from pathlib import Path

    return Path(__file__).resolve().parent / "e2e" / "fixtures" / _FLOW_E2E_FIXTURE


def build_flow_e2e_fixture_response() -> dict:
    """The REAL /api/order-flow/options-microstructure response for one deterministic
    replayed book + L1 tape, produced by the same route handler production serves.
    Inputs are the captured Schwab wire shapes pushed through the live state singleton
    (the daemon-plane feed's own producer path)."""
    import app.options.order_flow.state as ofls
    import server as srv

    c = _FLOW_E2E_CONTRACT
    t0 = _FLOW_E2E_BOOK_TIME_MS
    ofls.clear_all_live_state()
    try:
        ofls.push_book(c, {
            "key": c, "BOOK_TIME": t0,
            "BIDS": [{"BID_PRICE": 1.20, "TOTAL_VOLUME": 40},
                     {"BID_PRICE": 1.19, "TOTAL_VOLUME": 80},
                     {"BID_PRICE": 1.18, "TOTAL_VOLUME": 80}],
            "ASKS": [{"ASK_PRICE": 1.25, "TOTAL_VOLUME": 55},
                     {"ASK_PRICE": 1.26, "TOTAL_VOLUME": 85},
                     {"ASK_PRICE": 1.27, "TOTAL_VOLUME": 70}],
        })
        # Distinct vendor triples spanning the 5m / 2m / 30s tape windows so every PROXY
        # flow field is non-null (a null-only fixture could not prove value rendering).
        # Tape windows are relative to the newest vendor print clock; the top-of-book
        # BID/ASK_SIZE leaves resolve through the per-field wall-clock freshness boundary,
        # so those are pushed at the default (current) receive time.
        for dt_ms, price, size in ((-240_000, 1.20, 10), (-90_000, 1.24, 20),
                                   (-20_000, 1.22, 15), (0, 1.25, 30)):
            ofls.push_level_one(c, {
                "key": c, "BID_PRICE": 1.20, "ASK_PRICE": 1.25,
                "BID_SIZE": 40, "ASK_SIZE": 55,
                "LAST_PRICE": price, "LAST_SIZE": size,
                "TRADE_TIME_MILLIS": t0 + dt_ms,
            })
        return json.loads(srv.api_order_flow_options_microstructure(contract=c).body)
    finally:
        ofls.clear_all_live_state()


def write_flow_e2e_fixture() -> None:
    """Regeneration utility (never called by a test). The payload is built in a CHILD
    process whose environment carries the SAME process-private runtime boundary
    tests/conftest.py applies — set before any import, because this module itself imports
    stream_spine at load time (which resolves the stream DB) — so the generated fixture can
    never carry a live DB, token, or the production daemon's identity."""
    import os
    import shutil
    import subprocess
    import sys
    import tempfile

    root = tempfile.mkdtemp(prefix="ed-e2e-fixture-regen-")
    env = {k: v for k, v in os.environ.items()
           if k not in ("ED_CONSOLE_DB", "ED_DB_PATH", "STREAM_CAPTURE_DB_PATH")}
    env.update({
        "ED_RUNTIME_ROOT": root,
        "ED_ARTIFACTS_ROOT": os.path.join(root, "artifacts"),
        "ED_CONSOLE_ALLOW_NONCANONICAL_DB": "1",
        "ED_CI_OFFLINE": "1",
        "SCHWAB_API_KEY": "ci-placeholder-api-key",
        "SCHWAB_APP_SECRET": "ci-placeholder-app-secret",
        "SCHWAB_CALLBACK_URL": "https://127.0.0.1:8182",
        "ED_TERRAIN_QUARANTINE_LEDGER": os.path.join(root, "terrain_quarantine_ledger.jsonl"),
        "ED_GATE_CACHE_DISABLE": "1",
    })
    code = ("import json, sys; from tests.test_options_order_flow_production_v1 import "
            "build_flow_e2e_fixture_response as b; sys.stdout.write(json.dumps(b()))")
    repo_root = _flow_e2e_fixture_path().parents[3]     # tests/e2e/fixtures/<file> -> repo
    try:
        out = subprocess.run([sys.executable, "-c", code], env=env, capture_output=True,
                             text=True, check=True, cwd=str(repo_root)).stdout
    finally:
        shutil.rmtree(root, ignore_errors=True)
    payload = json.loads(out.strip().splitlines()[-1])   # import-time log lines may precede it
    # The only machine-specific VALUE: the child's temp stream-DB path. Keys are untouched.
    ident = payload.get("streaming_plane", {}).get("stream_db_identity")
    if isinstance(ident, dict) and "server_resolved_path" in ident:
        ident["server_resolved_path"] = "<isolated-runtime>/data/stream_capture.db"
    path = _flow_e2e_fixture_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def _key_paths(obj, prefix: str = "") -> set[str]:
    """Every dict key path (lists are not descended: their length is data, not contract)."""
    out: set[str] = set()
    if isinstance(obj, dict):
        for k, v in obj.items():
            p = f"{prefix}.{k}" if prefix else str(k)
            out.add(p)
            out |= _key_paths(v, p)
    return out


def test_flow_e2e_fixture_is_the_route_contract():
    """The committed Playwright fixture has exactly the route's key structure — so the Flow
    E2E proves compatibility with the REAL API shape, not with a shape the spec invented."""
    path = _flow_e2e_fixture_path()
    assert path.exists(), f"missing {path}; regenerate with write_flow_e2e_fixture()"
    fixture = json.loads(path.read_text(encoding="utf-8"))
    live = build_flow_e2e_fixture_response()
    assert _key_paths(fixture) == _key_paths(live), (
        "E2E fixture drifted from the route contract:\n"
        f"  only in fixture: {sorted(_key_paths(fixture) - _key_paths(live))}\n"
        f"  only in route:   {sorted(_key_paths(live) - _key_paths(fixture))}")
    # The defect this guards: flow fields live ONLY under `flow`, never flattened.
    for k in ("tape_pressure_30s", "tape_pressure_2m", "tape_pressure_5m",
              "cum_delta_proxy", "cum_delta_slope", "top_book_pressure",
              "native_aggressor_available"):
        assert k not in live, f"{k} must not be a top-level field"
        assert k in live["flow"]
        assert k in fixture["flow"]
    assert "classification" in live["flow"] and "classification" in live
    # Values that the E2E asserts on screen are served non-null by this replay.
    for k in ("tape_pressure_30s", "tape_pressure_2m", "tape_pressure_5m",
              "cum_delta_proxy", "cum_delta_slope", "top_book_pressure"):
        assert fixture["flow"][k] is not None, f"fixture flow.{k} is null"
    assert fixture["status"] == "ok"


def _isolated_stream_env(runtime_root):
    """Child env: an isolated ED_RUNTIME_ROOT, Schwab blocked.

    RC-534 disabled ambient STREAM_CAPTURE_DB_PATH / ED_CONSOLE_DB overrides — the daemon
    resolves its DB and owner lock CANONICALLY under ED_RUNTIME_ROOT (db_authority /
    stream_spine.resolve_stream_db_path). Isolation is one knob: point ED_RUNTIME_ROOT at a
    tmp dir and the daemon's DB/lock live at ``<root>/data/stream_capture.{db,lock}``.
    """
    import os
    from pathlib import Path as _P
    root = _P(runtime_root).resolve()
    env = os.environ.copy()
    env.pop("ED_CONSOLE_DB", None)
    env.pop("STREAM_CAPTURE_DB_PATH", None)
    env["ED_RUNTIME_ROOT"] = str(root)
    env["ED_ARTIFACTS_ROOT"] = str(root / "artifacts")
    env["ED_CI_OFFLINE"] = "1"
    env["SCHWAB_API_KEY"] = "ci-placeholder-key"
    env["SCHWAB_APP_SECRET"] = "ci-placeholder-secret"
    return env


def _canonical_stream_paths(runtime_root):
    """The daemon's canonical (db, lock) under an isolated ED_RUNTIME_ROOT."""
    from pathlib import Path as _P
    data = _P(runtime_root).resolve() / "data"
    return data / "stream_capture.db", data / "stream_capture.lock"


def test_real_subprocess_second_daemon_cannot_own_lock(tmp_path):
    """Real process boundary: a held DB-adjacent lock refuses a second daemon.

    Does not mock Popen. The second process is the real tools/run_stream_capture.py
    entry point. It must exit non-zero and must not be reported as started.
    """
    import subprocess
    import sys
    import time
    from pathlib import Path as _P

    repo = _P(__file__).resolve().parents[1]
    db, lock = _canonical_stream_paths(tmp_path)
    env = _isolated_stream_env(tmp_path)
    holder_src = (
        "import sys, time\n"
        f"sys.path.insert(0, r'{repo}')\n"
        "from app.market_data.schwab.streaming.capture import acquire_owner_lock\n"
        "fd, held = acquire_owner_lock()\n"
        "print('LOCK_HELD', held, flush=True)\n"
        "time.sleep(90)\n"
    )
    holder = subprocess.Popen(
        [sys.executable, "-c", holder_src],
        cwd=str(repo),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        env=env,
    )
    try:
        deadline = time.time() + 20
        saw_lock = False
        while time.time() < deadline:
            if lock.exists():
                saw_lock = True
                break
            if holder.poll() is not None:
                out, err = holder.communicate()
                raise AssertionError(
                    f"lock holder died rc={holder.returncode} stdout={out!r} stderr={err!r}"
                )
            time.sleep(0.05)
        assert saw_lock, "holder never created the DB-adjacent lock"
        second = subprocess.run(
            [
                sys.executable,
                "-m", "app.market_data.schwab.streaming.capture",
                "--symbols",
                "SPY",
                "--duration-min",
                "0",
            ],
            cwd=str(repo),
            capture_output=True,
            text=True,
            timeout=45,
            env=env,
        )
        combined = (second.stdout or "") + (second.stderr or "")
        assert second.returncode != 0, combined
        assert "another stream-capture owner" in combined, combined
        assert '"started"' not in combined
    finally:
        holder.kill()
        try:
            holder.wait(timeout=10)
        except subprocess.TimeoutExpired:
            holder.terminate()


def test_real_subprocess_failed_schwab_is_not_started(tmp_path):
    """Schwab/session failure is exit 2 and releases the lock. Not a success."""
    import subprocess
    import sys
    from pathlib import Path as _P

    repo = _P(__file__).resolve().parents[1]
    db, lock = _canonical_stream_paths(tmp_path)
    env = _isolated_stream_env(tmp_path)
    result = subprocess.run(
        [
            sys.executable,
            "-m", "app.market_data.schwab.streaming.capture",
            "--symbols",
            "SPY",
            "--duration-min",
            "0",
        ],
        cwd=str(repo),
        capture_output=True,
        text=True,
        timeout=45,
        env=env,
    )
    combined = (result.stdout or "") + (result.stderr or "")
    assert result.returncode == 2, combined
    assert "FATAL: Schwab client init failed" in combined, combined
    assert not lock.exists(), "failed start leaked the owner lock"
    assert '"started"' not in combined


def test_real_subprocess_dead_owner_lock_is_reclaimed(tmp_path):
    """After the owner process dies, the next real daemon can take the lock.

    It then fails Schwab honestly (exit 2) — reclaim is not a false start.
    """
    import subprocess
    import sys
    from pathlib import Path as _P

    repo = _P(__file__).resolve().parents[1]
    db, lock = _canonical_stream_paths(tmp_path)
    env = _isolated_stream_env(tmp_path)
    holder_src = (
        "import os, sys\n"
        f"sys.path.insert(0, r'{repo}')\n"
        "from app.market_data.schwab.streaming.capture import acquire_owner_lock\n"
        "fd, held = acquire_owner_lock()\n"
        "os._exit(0)\n"
    )
    died = subprocess.run(
        [sys.executable, "-c", holder_src],
        cwd=str(repo),
        capture_output=True,
        text=True,
        timeout=20,
        env=env,
    )
    assert died.returncode == 0, died.stdout + died.stderr
    assert lock.exists(), "crash must leave the lock file for the next owner to reclaim"
    result = subprocess.run(
        [
            sys.executable,
            "-m", "app.market_data.schwab.streaming.capture",
            "--symbols",
            "SPY",
            "--duration-min",
            "0",
        ],
        cwd=str(repo),
        capture_output=True,
        text=True,
        timeout=45,
        env=env,
    )
    combined = (result.stdout or "") + (result.stderr or "")
    assert result.returncode == 2, combined
    assert "another stream-capture owner" not in combined, combined
    assert "FATAL: Schwab client init failed" in combined, combined
    assert not lock.exists()


def test_options_api_carries_flow_block():
    import json
    import app.options.order_flow.state as ofls
    import server as srv

    contract = "SPY   260820C00767000"
    ofls.clear_all_live_state()
    ofls.push_book(contract, {
        "key": contract, "BOOK_TIME": int(time.time() * 1000),
        "BIDS": [{"BID_PRICE": 1.28, "TOTAL_VOLUME": 10}],
        "ASKS": [{"ASK_PRICE": 1.30, "TOTAL_VOLUME": 12}],
    })
    body = json.loads(srv.api_order_flow_options_microstructure(contract=contract).body)
    assert body["status"] == "ok"
    assert body["flow"]["classification"]["tape_pressure_30s"] == "PROXY"
    ofls.clear_all_live_state()
