"""Options/order-flow production path: default contract, live payload, history, stream lock.

# universal-scope-ok: fixtures use banked CDE/SPY contract rows as vendor-symbol
# examples of the enrolled-universe capture path, not a SPY-only product claim.
"""
from __future__ import annotations

import pytest

import json
import time


@pytest.fixture
def _at_capture(pin_clock):
    """The tests on the stored CDE chain are valued at its capture (2026-09-02 10:05 ET); the
    live-payload tests keep the real clock, since their book data is stamped with it."""
    return pin_clock(2026, 9, 2, 10, 5)


def _cde_fixture_chain():
    from pathlib import Path

    fx_path = Path(__file__).resolve().parent / "fixtures" / "real_cde_complete_chain_half_dollar.json"
    return json.loads(fx_path.read_text(encoding="utf-8"))


def test_pick_atm_call_uses_vendor_symbol_not_constructed(_at_capture):
    from app.options.contracts.default import pick_atm_call_symbol

    fx = _cde_fixture_chain()
    contracts = fx["chain"]
    calls = [c for c in contracts if str(c.get("putCall") or "").upper() == "CALL"]
    assert calls, "real CDE fixture must include CALL rows"
    spot = float(calls[0]["strikePrice"]) + 0.1
    picked = pick_atm_call_symbol(contracts, spot)
    assert picked is not None
    row = next(c for c in contracts if c.get("symbol") == picked)
    assert str(row.get("putCall") or "").upper() == "CALL"
    assert picked == row["symbol"]
    assert pick_atm_call_symbol(contracts, None) is None


def test_default_contract_is_the_front_expirys_atm_call_of_the_chain(monkeypatch, _at_capture):
    from app.options.contracts.default import front_atm_call, pick_atm_call_symbol

    fx = _cde_fixture_chain()
    monkeypatch.setattr("app.options.contracts.default._expiry_cutoff_et", lambda: fx["expiry"])
    later = [dict(c, expirationDate="2099-01-16T21:00:00.000+00:00") for c in fx["chain"]]
    assert front_atm_call(later + fx["chain"], 16.1) == pick_atm_call_symbol(fx["chain"], 16.1)
    assert front_atm_call(fx["chain"], None) is None


@pytest.mark.parametrize("day,hh,mm,want", [
    ("2026-11-27", 12, 59, "2026-11-27"),     # early close (13:00, time_et's calendar): still trading
    ("2026-11-27", 13, 30, "2026-11-28"),     # after the early close: today's expiry is done
    ("2026-09-25", 15, 59, "2026-09-25"),     # a full session
    ("2026-09-25", 16, 0, "2026-09-26"),
])
def test_the_default_contracts_expiry_cutoff_is_the_calendars_close(monkeypatch, day, hh, mm, want):
    """ONE-10: the cutoff was a fixed 16:00, so after a 13:00 early close the default contract
    could still be one that expired that afternoon."""
    import datetime as _dt
    from app.options.contracts import default as dflt
    from time_et import ET
    y, m, d = (int(x) for x in day.split("-"))
    monkeypatch.setattr(dflt, "now_et", lambda: _dt.datetime(y, m, d, hh, mm, tzinfo=ET))
    assert dflt._expiry_cutoff_et() == want


def test_live_payload_one_compute_includes_proxy_flow(monkeypatch):
    import app.options.order_flow.state as ofls
    from app.options.order_flow.live_payload import options_live_payload

    contract = "CDE   260904C00013000"
    ofls.clear_all_live_state()
    ofls.push_book(contract, {
        "key": contract,
        "BOOK_TIME": int(time.time() * 1000),
        "BIDS": [{"BID_PRICE": 1.10, "TOTAL_VOLUME": 40}],
        "ASKS": [{"ASK_PRICE": 1.20, "TOTAL_VOLUME": 50}],
    }, "OPTIONS_BOOK")
    ofls.push_level_one(contract, {
        "key": contract,
        "BID_PRICE": 1.10, "ASK_PRICE": 1.20,
        "LAST_PRICE": 1.15, "LAST_SIZE": 3,
        "TRADE_TIME_MILLIS": int(time.time() * 1000),
    }, ts_recv=time.time())
    payload = options_live_payload(contract, time.time())
    assert payload["status"] == "ok"
    assert "flow" in payload
    assert payload["flow"]["classification"]["cum_delta_proxy"] == "PROXY"
    assert payload["flow"]["native_aggressor_available"] is False
    ofls.clear_all_live_state()


# ─────────────────────────────────────────────────────────────────────────────
# E2E FIXTURE CONTRACT — the Playwright Flow spec (tests/e2e/console-gamma-flow.spec.js)
# stubs /api/order-flow/options-microstructure with tests/e2e/fixtures/
# options_microstructure_payload.json. That file is GENERATED by the real route handler
# below, never hand-written, and this test proves it still equals what the route serves
# today, key and value. A stub that drifts from the route is a false proof: the earlier
# Flow spec stubbed the flow fields FLATTENED at the top level while the route nests them
# under `flow`, and its green run proved nothing about the real API.
#
# Regenerate (from the repo root, project .venv):
#   python -c "from tests.test_options_order_flow_production_v1 import write_flow_e2e_fixture; write_flow_e2e_fixture()"
# ─────────────────────────────────────────────────────────────────────────────

_FLOW_E2E_CONTRACT = "SPY   260911C00100000"
_FLOW_E2E_FIXTURE = "options_microstructure_payload.json"
_FLOW_E2E_BOOK_TIME_MS = 1789000000000


def _flow_e2e_fixture_path():
    from pathlib import Path

    return Path(__file__).resolve().parent / "e2e" / "fixtures" / _FLOW_E2E_FIXTURE


def build_flow_e2e_fixture_response() -> dict:
    """The REAL /api/order-flow/options-microstructure response for one deterministic
    replayed book + L1 tape, produced by the same route handler production serves, at a
    pinned clock (the book's time) with the daemon holding the contract. Inputs are Schwab
    wire shapes handed to the console's own intake (streaming._ingest_pushed), as the
    daemon pushes them."""
    from unittest import mock

    import app.options.order_flow.state as ofls
    import live_market_plane as lmp
    import server as srv
    from app.options.order_flow import streaming as ofs

    c = _FLOW_E2E_CONTRACT
    t0 = _FLOW_E2E_BOOK_TIME_MS
    now = t0 / 1000.0
    ofls.clear_all_live_state()
    with mock.patch("time.time", lambda: now):
        try:
            lmp.record_feed_heartbeat({"ts": now, "schwab_socket_open": True,
                                       "held": {"LEVELONE_OPTIONS": [c], "OPTIONS_BOOK": [c]}})
            ofs._ingest_pushed(f"book.{c}", {"symbol": c, "ts_recv": now, "service": "OPTIONS_BOOK",
                                             "content": {
                "key": c, "BOOK_TIME": t0,
                "BIDS": [{"BID_PRICE": 1.20, "TOTAL_VOLUME": 40},
                         {"BID_PRICE": 1.19, "TOTAL_VOLUME": 80},
                         {"BID_PRICE": 1.18, "TOTAL_VOLUME": 80}],
                "ASKS": [{"ASK_PRICE": 1.25, "TOTAL_VOLUME": 55},
                         {"ASK_PRICE": 1.26, "TOTAL_VOLUME": 85},
                         {"ASK_PRICE": 1.27, "TOTAL_VOLUME": 70}]}})
            # Distinct vendor triples spanning the 5m / 2m / 30s tape windows so every PROXY
            # flow field is non-null (a null-only fixture could not prove value rendering).
            for dt_ms, price, size in ((-240_000, 1.20, 10), (-90_000, 1.24, 20),
                                       (-20_000, 1.22, 15), (0, 1.25, 30)):
                ofs._ingest_pushed(f"optquote.{c}", {"symbol": c, "ts_recv": now + dt_ms / 1000.0,
                                                     "content": {
                    "key": c, "BID_PRICE": 1.20, "ASK_PRICE": 1.25,
                    "BID_SIZE": 40, "ASK_SIZE": 55,
                    "LAST_PRICE": price, "LAST_SIZE": size,
                    "TRADE_TIME_MILLIS": t0 + dt_ms}})
            return json.loads(srv.api_order_flow_options_microstructure(contract=c).body)
        finally:
            lmp.record_feed_down()
            ofls.clear_all_live_state()


def write_flow_e2e_fixture() -> None:
    """Regeneration utility (never called by a test). The payload is built in a CHILD
    process whose environment carries the SAME process-private runtime boundary
    tests/conftest.py applies — set before any import, because this module itself imports
    stream_spine at load time (which resolves the stream DB) — so the generated fixture can
    never carry a live DB, token, or the production daemon's identity."""
    import os
    import shutil
    import subprocess
    import sys
    import tempfile

    root = tempfile.mkdtemp(prefix="ed-e2e-fixture-regen-")
    env = {k: v for k, v in os.environ.items()
           if k not in ("ED_CONSOLE_DB", "ED_DB_PATH", "STREAM_CAPTURE_DB_PATH")}
    env.update({
        "ED_RUNTIME_ROOT": root,
        "ED_ARTIFACTS_ROOT": os.path.join(root, "artifacts"),
        "ED_CONSOLE_ALLOW_NONCANONICAL_DB": "1",
        "ED_CI_OFFLINE": "1",
        "SCHWAB_API_KEY": "ci-placeholder-api-key",
        "SCHWAB_APP_SECRET": "ci-placeholder-app-secret",
        "SCHWAB_CALLBACK_URL": "https://127.0.0.1:8182",
    })
    code = ("import json, sys; from tests.test_options_order_flow_production_v1 import "
            "build_flow_e2e_fixture_response as b; sys.stdout.write(json.dumps(b()))")
    repo_root = _flow_e2e_fixture_path().parents[3]     # tests/e2e/fixtures/<file> -> repo
    try:
        out = subprocess.run([sys.executable, "-c", code], env=env, capture_output=True,
                             text=True, check=True, cwd=str(repo_root)).stdout
    finally:
        shutil.rmtree(root, ignore_errors=True)
    payload = json.loads(out.strip().splitlines()[-1])   # import-time log lines may precede it
    # The only machine-specific VALUE: the child's temp stream-DB path. Keys are untouched.
    ident = payload.get("streaming_plane", {}).get("stream_db_identity")
    if isinstance(ident, dict) and "server_resolved_path" in ident:
        ident["server_resolved_path"] = "<isolated-runtime>/data/stream_capture.db"
    path = _flow_e2e_fixture_path()
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def test_flow_e2e_fixture_is_the_route_contract():
    """The committed Playwright fixture is exactly what the route serves for the replay, every
    key and value -- so the Flow E2E proves the REAL API's output, not a shape the spec
    invented or values the route no longer produces."""
    path = _flow_e2e_fixture_path()
    assert path.exists(), f"missing {path}; regenerate with write_flow_e2e_fixture()"
    fixture = json.loads(path.read_text(encoding="utf-8"))
    live = build_flow_e2e_fixture_response()
    assert fixture == live, "E2E fixture drifted from the route; regenerate with write_flow_e2e_fixture()"
    # The defect this guards: flow fields live ONLY under `flow`, never flattened.
    for k in ("tape_pressure_30s", "tape_pressure_2m", "tape_pressure_5m",
              "cum_delta_proxy", "cum_delta_slope", "top_book_pressure",
              "native_aggressor_available"):
        assert k not in live, f"{k} must not be a top-level field"
        assert k in live["flow"]
        assert k in fixture["flow"]
    assert "classification" in live["flow"] and "classification" in live
    # Values that the E2E asserts on screen are served non-null by this replay.
    for k in ("tape_pressure_30s", "tape_pressure_2m", "tape_pressure_5m",
              "cum_delta_proxy", "cum_delta_slope", "top_book_pressure"):
        assert fixture["flow"][k] is not None, f"fixture flow.{k} is null"
    assert fixture["status"] == "ok"


def test_options_api_carries_flow_block():
    import json
    import app.options.order_flow.state as ofls
    import server as srv

    contract = "SPY   260820C00767000"
    ofls.clear_all_live_state()
    ofls.push_book(contract, {
        "key": contract, "BOOK_TIME": int(time.time() * 1000),
        "BIDS": [{"BID_PRICE": 1.28, "TOTAL_VOLUME": 10}],
        "ASKS": [{"ASK_PRICE": 1.30, "TOTAL_VOLUME": 12}],
    }, "OPTIONS_BOOK")
    body = json.loads(srv.api_order_flow_options_microstructure(contract=contract).body)
    assert body["status"] == "ok"
    assert body["flow"]["classification"]["tape_pressure_30s"] == "PROXY"
    ofls.clear_all_live_state()
