"""Mega 3 traceable inventory (§H+§I) — MC/regime + features."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Mega3Disposition = Literal["SCHWAB_LEAF", "REPLACED", "DERIVED", "ALLOWLISTED", "NONE"]


@dataclass(frozen=True)
class Mega3TraceableDerivation:
    file: str
    line: int
    derivation: str
    disposition: Mega3Disposition
    schwab_leaf: str | None
    producer_refs: tuple[str, ...]
    allowlist_id: str | None
    justification: str


MEGA3_FILES = frozenset(
    {
        "features/canonical_contract.py",
        "features/cascade_stack_contract.py",
        "features/cascade_stack_schema.py",
        "features/db_feature_adapter.py",
        "features/feature_gap_report.py",
        "features/fusion_model_input.py",
        "features/fusion_policy_contract.py",
        "features/fusion_replay_grade_v1.py",
        "features/inference_snapshot.py",
        "features/live_feature_adapter.py",
        "features/lstm_sequence_input.py",
        "features/monte_carlo_stack_input.py",
        "features/mvp_source_coercion.py",
        "features/parallel_stack_schema.py",
        "features/regime_mvp_context.py",
        "features/replay_signal_input_v1.py",
        "features/semantic_parity.py",
        "features/shared_sequence_context.py",
        "features/signal_layer_v1.py",
        "features/stack_integrity_v1.py",
        "features/training_canonical_input.py",
        "features/xgb_model_input.py",
        "mc_fusion_adjustment.py",
        "monte_carlo.py",
        "regime_engine.py",
        "volatility_regime.py",
    }
)

MEGA3_TRACEABLE_INVENTORY: tuple[Mega3TraceableDerivation, ...] = (
    Mega3TraceableDerivation("features/canonical_contract.py", 251, "get_mvp_feature_names", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for get_mvp_feature_names output fields."),
    Mega3TraceableDerivation("features/canonical_contract.py", 256, "get_feature_spec", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for get_feature_spec output fields."),
    Mega3TraceableDerivation("features/canonical_contract.py", 263, "get_mvp_field_semantics", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for get_mvp_field_semantics output fields."),
    Mega3TraceableDerivation("features/canonical_contract.py", 270, "validate_feature_contract_row", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/canonical_contract.py", 344, "excluded_from_mvp", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/cascade_stack_contract.py", 68, "validate_cascade_inference_lineage", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/cascade_stack_contract.py", 124, "assert_no_legacy_mvp_in_fusion_overlay", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for assert_no_legacy_mvp_in_fusion_overlay output fields."),
    Mega3TraceableDerivation("features/cascade_stack_schema.py", 28, "build_cascade_challenger_run_metadata", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/db_feature_adapter.py", 20, "build_db_mvp_feature_row", "DERIVED", None, ("features/inference_snapshot.py:build_inference_snapshot_v1",), None, "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_db_mvp_feature_row)."),
    Mega3TraceableDerivation("features/feature_gap_report.py", 10, "compare_live_and_db_feature_support", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 28, "similar_setup_filters_from_canonical_features", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for similar_setup_filters_from_canonical_features output fields."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 50, "similar_setup_filters_from_db_snapshot_row", "DERIVED", None, ("features/db_feature_adapter.py:build_db_mvp_feature_row", "features/fusion_model_input.py:similar_setup_filters_from_canonical_features",), None, "Composes Mega1 producers for similar_setup_filters_from_db_snapshot_row output fields."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 65, "strip_mvp_keys_from_fusion_overlay", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for strip_mvp_keys_from_fusion_overlay output fields."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 70, "assert_fusion_overlay_has_no_mvp_keys", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for assert_fusion_overlay_has_no_mvp_keys output fields."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 79, "validate_inference_snapshot_for_fusion_stack", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 129, "_meta_encode_column_value", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 144, "meta_tabular_vector_from_overlay", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 151, "meta_tabular_input_dim", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_model_input.py", 157, "apply_ablation_knockout_columns", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 15, "_fusion_triplet", "NONE", None, (), None, "No market-field derivation: AST-listed _fusion_triplet; no legacy row."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 15, "fusion_payload_to_policy_columns", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (fusion_payload_to_policy_columns)."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 34, "_stack_status", "NONE", None, (), None, "No market-field derivation: AST-listed _stack_status; no legacy row."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 43, "fusion_policy_columns_horizon_failed", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Internal helper returning the canonical-failed column tuple for a horizon; not Schwab wire derivation (fusion_policy_columns_horizon_failed)."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 58, "policy_move_column", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_policy_contract.py", 62, "policy_dir_up_column", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/fusion_replay_grade_v1.py", 9, "fusion_replay_stack_grade_v1", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 26, "build_feature_lineage_map", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_feature_lineage_map)."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 46, "_feature_quality_from_row", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _feature_quality_from_row output fields."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 56, "build_inference_snapshot_v1_from_feature_row", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 95, "build_inference_snapshot_v1_from_db_row", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_inference_snapshot_v1_from_db_row)."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 113, "build_inference_snapshot_v1_from_signal_input", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_inference_snapshot_v1_from_signal_input)."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 118, "build_inference_snapshot_v1_from_signal_input._dist_to_vwap_pts", "DERIVED", None, ("features/inference_snapshot.py:build_inference_snapshot_v1_from_signal_input",), None, "Composes Mega1 producers for _dist_to_vwap_pts output fields."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 157, "build_inference_snapshot_v1", "DERIVED", None, ("market_state.py:build_market_state",), None, "Canonical inference row from upstream market state."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 206, "_assert_inference_snapshot_v1", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 292, "_lineage_entry", "NONE", None, (), None, "No market-field derivation: metadata envelope builder for operator field_lineage entries."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 314, "_quote_field_lineage", "DERIVED", None, ("server.py:_fetch_state",), None, "Classifies existing quote_source_detail keys; no wire read or value mutation."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 356, "build_operator_field_lineage", "DERIVED", None, ("server.py:_fetch_state", "market_state.py:build_market_state",), None, "Classifies existing Tier-C md keys into field_lineage map; no wire read or value mutation."),
    Mega3TraceableDerivation("features/inference_snapshot.py", 464, "attach_operator_field_lineage", "NONE", None, (), None, "No market-field derivation: in-place attach of field_lineage metadata to payload dict."),
    Mega3TraceableDerivation("features/live_feature_adapter.py", 25, "build_live_mvp_feature_row", "DERIVED", None, ("market_state.py:build_market_state",), None, "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_live_mvp_feature_row)."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 82, "_canonical_missing_masks", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _canonical_missing_masks output fields."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 86, "_patch_lstm_categoricals", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _patch_lstm_categoricals output fields."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 107, "encode_lstm_structure_bar_with_masks", "DERIVED", None, ("features/lstm_sequence_input.py:_patch_lstm_categoricals", "features/lstm_sequence_input.py:_canonical_missing_masks",), None, "Composes Mega1 producers for encode_lstm_structure_bar_with_masks output fields."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 118, "_canonical_features_for_merged_row", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 123, "encode_lstm_micro_bar_with_masks", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 131, "encode_lstm_structure_sequence_bar", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 135, "merge_db_row_with_canonical_mvp", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for merge_db_row_with_canonical_mvp output fields."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 149, "_ts_close", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 151, "encode_lstm_micro_sequence_bar", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 158, "build_lstm_merged_windows", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 166, "encode_lstm_structure_sequence_bar_for_checkpoint", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 194, "encode_lstm_micro_sequence_bar_for_checkpoint", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/lstm_sequence_input.py", 217, "build_transformer_merged_window", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_transformer_merged_window)."),
    Mega3TraceableDerivation("features/monte_carlo_stack_input.py", 31, "resolve_monte_carlo_stack_inputs", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for resolve_monte_carlo_stack_inputs output fields."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 27, "_contains_key", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 34, "_require_mapping", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Internal type-guard helper for source-mapping inputs; not Schwab wire derivation (_require_mapping)."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 34, "strict_float_from_raw", "DERIVED", None, ("market_state.py:build_market_state",), None, "Fail-closed numeric coercion; no silent default to 0."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 53, "read_optional_float", "DERIVED", None, ("features/mvp_source_coercion.py:strict_float_from_raw", "market_state.py:build_market_state",), None, "Composes Mega1 producers for read_optional_float output fields."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 66, "read_optional_zone", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 88, "read_optional_vwap_side", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/mvp_source_coercion.py", 110, "read_liquidity_summary_subdict", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for read_liquidity_summary_subdict output fields."),
    Mega3TraceableDerivation("features/parallel_stack_schema.py", 31, "_normalize_triplet", "NONE", None, (), None, "No market-field derivation: AST-listed _normalize_triplet; no legacy row."),
    Mega3TraceableDerivation("features/parallel_stack_schema.py", 31, "empty_parallel_output", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/parallel_stack_schema.py", 47, "build_unified_stack_layer_output", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 19, "require_mvp_features", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for require_mvp_features output fields."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 26, "mvp_zone", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 33, "mvp_spot", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for mvp_spot output fields."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 45, "mvp_vwap_side", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for mvp_vwap_side output fields."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 52, "mvp_nearest_distances_for_regime", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for mvp_nearest_distances_for_regime output fields."),
    Mega3TraceableDerivation("features/regime_mvp_context.py", 59, "mvp_net_gamma", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for mvp_net_gamma output fields."),
    Mega3TraceableDerivation("features/replay_signal_input_v1.py", 16, "_positive_float_required", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _positive_float_required output fields."),
    Mega3TraceableDerivation("features/replay_signal_input_v1.py", 29, "signal_input_from_snapshot_row_dict", "DERIVED", None, ("features/replay_signal_input_v1.py:_positive_float_required",), None, "Composes Mega1 producers for signal_input_from_snapshot_row_dict output fields."),
    Mega3TraceableDerivation("features/replay_signal_input_v1.py", 30, "_replay_vol_decimal", "DERIVED", None, ("market_state.py:build_market_state",), None, "VOL_INPUT_CONTRACT 1.0.0 replay unit boundary (VOL-UNIT-001): persisted percent-form iv_level/realized_vol (stamped by the canonical builder) -> canonical decimal via the same vol_percent_to_decimal as the live stamp (idempotent for already-decimal, so no double conversion); missing/invalid/nonfinite -> None (fail-closed, never directional evidence). Locked by tests/test_replay_signal_input_v1.py GR-1/GR-2/GR-3."),
    Mega3TraceableDerivation("features/semantic_parity.py", 17, "assert_live_db_canonicalization_equivalent", "DERIVED", None, ("features/live_feature_adapter.py:build_live_mvp_feature_row", "features/db_feature_adapter.py:build_db_mvp_feature_row",), None, "Composes Mega1 producers for assert_live_db_canonicalization_equivalent output fields."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 23, "_require_ticker", "NONE", None, (), None, "No market-field derivation: AST-listed _require_ticker; no legacy row."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 33, "_max_transformer_seq_len_for_ticker", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _max_transformer_seq_len_for_ticker output fields."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 51, "_seq_len_from_transformer_meta", "NONE", None, (), None, "No market-field derivation: transformer meta JSON key alias reader; not Schwab wire."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 63, "build_shared_sequence_context", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (build_shared_sequence_context)."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 132, "transformer_window_chronological", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for transformer_window_chronological output fields."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 226, "_guest_wire_row_from_live", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/shared_sequence_context.py", 258, "build_guest_wire_sequence_context", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 34, "_f", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 43, "meta_n_bars_int", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Internal meta-bar count coercion helper; not Schwab wire derivation (meta_n_bars_int)."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 46, "_clip", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 50, "_safe_div", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _safe_div output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 56, "_tr", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 71, "_atr", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 83, "_percentile_rank_window", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 92, "_ols_slope_yx", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 106, "_ols_log_slope_close", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 114, "_fractal_swings", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _fractal_swings output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 141, "_aggregate_bars", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _aggregate_bars output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 168, "_sign_trend", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 178, "_volume_profile_proxy", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _volume_profile_proxy output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 228, "load_bars_before_decision", "ALLOWLISTED", None, (), 'mega1_sqlite_internal', "Reads persisted snapshot SQLite rows, not Schwab wire JSON (load_bars_before_decision)."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 257, "compute_signal_layer_v1", "DERIVED", None, ("market_state.py:build_market_state", "features/signal_layer_v1.py:_fractal_swings", "features/signal_layer_v1.py:_volume_profile_proxy", "features/signal_layer_v1.py:_aggregate_bars", "features/signal_layer_v1.py:_safe_div",), None, "Composes Mega1 producers for compute_signal_layer_v1 output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 596, "compute_signal_layer_v1_from_db", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 609, "_sqlite_conn_from_db", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 619, "compute_signal_layer_v1_for_calibration", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 640, "layer_direction_policy", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for layer_direction_policy output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 663, "signal_layer_v1_to_direction_probs", "DERIVED", None, ("features/signal_layer_v1.py:flatten_numeric_features",), None, "Composes Mega1 producers for signal_layer_v1_to_direction_probs output fields."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 664, "compute_price_action_snapshot_columns", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/signal_layer_v1.py", 694, "flatten_numeric_features", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for flatten_numeric_features output fields."),
    Mega3TraceableDerivation("features/stack_integrity_v1.py", 15, "record_stack_degradation", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/stack_integrity_v1.py", 45, "merge_stack_integrity_events", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/stack_integrity_v1.py", 55, "finalize_stack_integrity_v1", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 30, "training_canonical_lineage_header", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 38, "assert_training_lineage_matches_canonical", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 55, "training_snapshot_for_sequence_encode", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 72, "_row_dict_from_df", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 76, "validate_tabular_training_dataframe_canonical", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 81, "normalize_pandas_sql_null_row_dict", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 102, "records_for_mvp_from_dataframe", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 107, "assert_shared_feature_cache_keys_equal", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for assert_shared_feature_cache_keys_equal output fields."),
    Mega3TraceableDerivation("features/training_canonical_input.py", 174, "preflight_tickers_for_training", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 47, "validate_inference_snapshot_v1_envelope", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 73, "validate_inference_snapshot_v1_for_xgb", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 90, "_et_from_ts_utc", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 95, "inference_snapshot_v1_to_engineering_snapshot", "NONE", None, (), None, "Schema/contract validation; no market-field derivation."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 119, "merge_xgb_fusion_overlay", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for merge_xgb_fusion_overlay output fields."),
    Mega3TraceableDerivation("features/xgb_model_input.py", 137, "assert_not_raw_l1_payload", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for assert_not_raw_l1_payload output fields."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 18, "normalize_mc", "DERIVED", None, ("market_state.py:build_market_state",), None, "Normalizes MC output relative to spot."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 52, "_triplet", "ALLOWLISTED", None, (), 'mega3_internal_helper', "Pure probability blending helper."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 60, "_argmax_dir", "ALLOWLISTED", None, (), 'mega3_internal_helper', "Pure probability blending helper."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 64, "_blend_uniform", "ALLOWLISTED", None, (), 'mega3_internal_helper', "Pure probability blending helper."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 74, "_max_uniform_blend_preserving_argmax", "ALLOWLISTED", None, (), 'mega3_internal_helper', "Pure probability blending helper."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 95, "_add_to_flat_from_others", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 105, "_add_to_flat_from_others.pool_order", "NONE", None, (), None, "No market-field derivation: Nested helper inside _add_to_flat_from_others; parent row owns derivation semantics."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 132, "_max_tail_flat_delta", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 151, "_apply_directional_bias", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 184, "apply_mc_adjustment", "DERIVED", None, ("mc_fusion_adjustment.py:_triplet", "mc_fusion_adjustment.py:_argmax_dir", "mc_fusion_adjustment.py:_max_uniform_blend_preserving_argmax", "mc_fusion_adjustment.py:_blend_uniform", "market_state.py:build_market_state",), None, "Blends MC path features into fusion probabilities."),
    Mega3TraceableDerivation("mc_fusion_adjustment.py", 236, "fuse_payload_apply_mc_adjustment", "DERIVED", None, ("mc_fusion_adjustment.py:normalize_mc", "mc_fusion_adjustment.py:apply_mc_adjustment", "mc_fusion_adjustment.py:_argmax_dir",), None, "Applies MC adjustment on fusion payload object."),
    Mega3TraceableDerivation("monte_carlo.py", 91, "MonteCarloOutput.mc_feature_dict", "DERIVED", None, ("market_state.py:build_market_state",), None, "MC feature dict for fusion; not quote fields."),
    Mega3TraceableDerivation("monte_carlo.py", 78, "mc_sigma_unit_for_row", "NONE", None, (), None, "No market-field derivation: classifies the unit era of a stored mc_sigma_value row (RC-478 mixed-unit quarantine)."),
    Mega3TraceableDerivation("monte_carlo.py", 103, "_blend_sigma", "DERIVED", None, ("market_state.py:build_market_state",), None, "Sigma blend; inputs from Schwab-first chain/candles upstream."),
    Mega3TraceableDerivation("monte_carlo.py", 127, "_compute_drift", "DERIVED", None, ("market_state.py:build_market_state",), None, "Drift from regime + model confidence; not a Schwab leaf."),
    Mega3TraceableDerivation("monte_carlo.py", 145, "simulate", "DERIVED", None, ("market_state.py:build_market_state", "monte_carlo.py:_compute_drift", "monte_carlo.py:_blend_sigma",), None, "MC paths from upstream vol/spot; no Schwab wire ingest."),
    Mega3TraceableDerivation("monte_carlo.py", 377, "_fallback", "NONE", None, (), None, "No market-field derivation: MC fallback error payload."),
    Mega3TraceableDerivation("regime_engine.py", 95, "_micro_regimes", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _micro_regimes output fields."),
    Mega3TraceableDerivation("regime_engine.py", 116, "_score_pinning", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_pinning output fields."),
    Mega3TraceableDerivation("regime_engine.py", 160, "_score_acceleration", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_acceleration output fields."),
    Mega3TraceableDerivation("regime_engine.py", 206, "_score_breakout", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_breakout output fields."),
    Mega3TraceableDerivation("regime_engine.py", 242, "_score_mean_reversion", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_mean_reversion output fields."),
    Mega3TraceableDerivation("regime_engine.py", 276, "_score_vol_compression", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_vol_compression output fields."),
    Mega3TraceableDerivation("regime_engine.py", 313, "_score_vol_expansion", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_vol_expansion output fields."),
    Mega3TraceableDerivation("regime_engine.py", 346, "_score_trend_continuation", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_trend_continuation output fields."),
    Mega3TraceableDerivation("regime_engine.py", 379, "_score_reversal_prone", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _score_reversal_prone output fields."),
    Mega3TraceableDerivation("regime_engine.py", 434, "classify_regime", "DERIVED", None, ("market_state.py:build_market_state",), None, "8-family regime from upstream levels/greeks/zone."),
    Mega3TraceableDerivation("regime_engine.py", 534, "_unknown_regime", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _unknown_regime output fields."),
    Mega3TraceableDerivation("volatility_regime.py", 56, "classify_volatility_regime", "DERIVED", None, ("market_state.py:build_market_state",), None, "Vol policy from rv/iv/atr/vix upstream fields."),
    Mega3TraceableDerivation("volatility_regime.py", 89, "normalize_vol_decimal", "NONE", None, (), None, "No market-field derivation: Schwab decimal contract guard; percentage heuristic scale only."),
    Mega3TraceableDerivation("volatility_regime.py", 108, "vol_percent_to_decimal", "NONE", None, (), None, "No market-field derivation: percent-to-decimal unit converter at SignalInput stamp; not Schwab wire."),
    Mega3TraceableDerivation("volatility_regime.py", 112, "_safe_floats", "NONE", None, (), None, "No market-field derivation: AST-listed _safe_floats; no legacy row."),
    Mega3TraceableDerivation("volatility_regime.py", 130, "_garch_trend", "NONE", None, (), None, "No market-field derivation: AST-listed _garch_trend; no legacy row."),
    Mega3TraceableDerivation("volatility_regime.py", 222, "_f", "NONE", None, (), None, "No market-field derivation: Scoring/helper; no new market-field derivation."),
)

