"""Mega 1 traceable inventory (§A+§B+§C) — TraceableDerivation rows per AC."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

Mega1Disposition = Literal["SCHWAB_LEAF", "REPLACED", "DERIVED", "ALLOWLISTED", "NONE"]


@dataclass(frozen=True)
class Mega1TraceableDerivation:
    file: str
    line: int
    derivation: str
    disposition: Mega1Disposition
    schwab_leaf: str | None
    producer_refs: tuple[str, ...]
    allowlist_id: str | None
    justification: str


MEGA1_FILES = frozenset(
    {
        "live_decision_bundle.py",
        "live_market_plane.py",
        "live_pipeline_diag.py",
        "live_vs_replay_validation.py",
        "market_context.py",
        "market_data_adapter.py",
        "market_state.py",
        "math_snapshot_derive.py",
        "polling_adapter.py",
        "reauth_schwab.py",
        "schwab_client.py",
        "server.py",
        "snapshot_access.py",
        "snapshot_normalizer.py",
        "sse_adapter.py",
        "websocket_adapter.py",
    }
)

MEGA1_TRACEABLE_INVENTORY: tuple[Mega1TraceableDerivation, ...] = (
    Mega1TraceableDerivation("live_decision_bundle.py", 52, "stamp_decision_bundle", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_decision_bundle.py", 74, "_float_or_none", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_decision_bundle.py", 94, "_key_levels_from_ms_dict", "DERIVED", None, ("market_state.py:build_market_state", "server.py:_fetch_state",), None, "Extracts level tuples from cached state."),
    Mega1TraceableDerivation("live_decision_bundle.py", 146, "recompute_nearest_struct_at_spot", "DERIVED", None, ("live_decision_bundle.py:_key_levels_from_ms_dict",), None, "Nearest wall recompute at stream spot."),
    Mega1TraceableDerivation("live_decision_bundle.py", 198, "_session_bucket_et", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_session_bucket_et)."),
    Mega1TraceableDerivation("live_decision_bundle.py", 210, "_session_bucket_from_utc_ts", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_decision_bundle.py", 220, "_live_session_label", "DERIVED", None, ("server.py:_fetch_state",), None, "Session label via market_context."),
    Mega1TraceableDerivation("live_decision_bundle.py", 238, "tick_triggers_coherent_refresh", "DERIVED", None, ("server.py:_fetch_state", "live_decision_bundle.py:_live_session_label", "live_decision_bundle.py:recompute_nearest_struct_at_spot",), None, "Coherence triggers vs stream spot and cached bundle."),
    Mega1TraceableDerivation("live_market_plane.py", 37, "next_fast_generation", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_market_plane.py", 46, "_safe_float", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_market_plane.py", 58, "_plane_tuple_sig", "DERIVED", None, ("server.py:_fetch_state",), None, "Dedup signature for plane tuple."),
    Mega1TraceableDerivation("live_market_plane.py", 66, "_positive_float", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_market_plane.py", 73, "_epoch_seconds_from_millis", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_market_plane.py", 80, "record_from_level_one_equity", "DERIVED", None, ("server.py:_fetch_state", "live_market_plane.py:_plane_tuple_sig",), None, "Delegates to Schwab transport producers for record_from_level_one_equity."),
    Mega1TraceableDerivation("live_market_plane.py", 192, "record_quote", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Records REST-shaped quote into plane cache."),
    Mega1TraceableDerivation("live_market_plane.py", 207, "get_quote", "DERIVED", None, ("schwab_client.py:safe_get_quote",), None, "Delegates to Schwab transport producers for get_quote."),
    Mega1TraceableDerivation("live_market_plane.py", 215, "merge_into_state", "DERIVED", None, ("server.py:_fetch_state", "live_market_plane.py:get_quote",), None, "Delegates to Schwab transport producers for merge_into_state."),
    Mega1TraceableDerivation("live_market_plane.py", 249, "apply_l1_live_quote_overlay", "DERIVED", None, ("live_market_plane.py:get_quote",), None, "Delegates to Schwab transport producers for apply_l1_live_quote_overlay."),
    Mega1TraceableDerivation("live_market_plane.py", 287, "take_fresh_sse_quote_payload", "DERIVED", None, ("server.py:_fetch_state",), None, "Delegates to Schwab transport producers for take_fresh_sse_quote_payload."),
    Mega1TraceableDerivation("live_market_plane.py", 310, "reset_sse_push_cursor", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (reset_sse_push_cursor)."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 31, "_live_diag_on", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 36, "_avail", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 40, "_fus_pack", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 51, "_serialize_predictive", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 92, "_serialize_mh_bundle", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 142, "emit_compute_signals_diag", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 201, "emit_api_state_cache", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_pipeline_diag.py", 220, "emit_fetch_state_start", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 41, "_validation_quality_status", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 54, "_row_get", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 60, "_exp_key", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 66, "_normalize_side", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 70, "_replay_one_row", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_replay_one_row)."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 122, "_live_expiry_from_proof", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_live_expiry_from_proof)."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 131, "_live_from_row", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_live_from_row)."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 175, "run_live_vs_replay_validation", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (run_live_vs_replay_validation)."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 359, "run_live_vs_replay_validation._rate", "NONE", None, (), None, "No market-field derivation: Nested helper inside run_live_vs_replay_validation; parent row owns derivation semantics."),
    Mega1TraceableDerivation("live_vs_replay_validation.py", 485, "main", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("market_context.py", 15, "_positive_float_or_none", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("market_context.py", 25, "_float_or_none", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("market_context.py", 34, "configured_index_futures_symbols", "ALLOWLISTED", None, (), "mega1_env_config", "Composes Mega1 producers for configured_index_futures_symbols output fields."),
    Mega1TraceableDerivation("market_context.py", 114, "market_context_panel_symbols_excluding_core", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Schwab API or wire JSON ingest path."),
    Mega1TraceableDerivation("market_context.py", 125, "market_context_panel_symbols_excluding_core.add", "NONE", None, (), None, "No market-field derivation: Nested helper inside market_context_panel_symbols_excluding_core; parent row owns derivation semantics."),
    Mega1TraceableDerivation("market_context.py", 251, "_vix_regime", "DERIVED", None, ("market_context.py:fetch_market_context",), None, "Composes Mega1 producers for _vix_regime output fields."),
    Mega1TraceableDerivation("market_context.py", 262, "_dot_color", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_context.py", 270, "_extract_quote", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Schwab quote hierarchy; pct from netChange when percent leaf absent."),
    Mega1TraceableDerivation("market_context.py", 301, "_build_confluence", "DERIVED", None, ("market_context.py:fetch_market_context",), None, "Cap-weighted confluence from quote-derived chg_pct inputs."),
    Mega1TraceableDerivation("market_context.py", 351, "_build_iwm_confluence", "DERIVED", None, ("market_context.py:fetch_market_context",), None, "IWM sector confluence composite."),
    Mega1TraceableDerivation("market_context.py", 398, "iwm_blended_participation_push", "DERIVED", None, ("market_context.py:fetch_market_context",), None, "Composes Mega1 producers for iwm_blended_participation_push output fields."),
    Mega1TraceableDerivation("market_context.py", 421, "_derive_session", "ALLOWLISTED", None, (), "mega1_session_calendar", "ET session label; no Schwab session_label leaf."),
    Mega1TraceableDerivation("market_context.py", 445, "fetch_market_context", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Multi-symbol quote fetch via safe_get_quote wrapper."),
    Mega1TraceableDerivation("market_context.py", 458, "fetch_market_context._fetch", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Nested per-symbol quote fetch inside fetch_market_context."),
    Mega1TraceableDerivation("market_context.py", 467, "fetch_market_context._chg_for", "SCHWAB_LEAF", "quotes.quote.netPercentChange", (), None, "Nested pct change helper from quote JSON."),
    Mega1TraceableDerivation("market_context.py", 601, "proximity_alerts", "DERIVED", None, ("market_context.py:proximity_alerts._check",), None, "Distance alerts vs key levels; inputs from upstream math."),
    Mega1TraceableDerivation("market_context.py", 610, "proximity_alerts._check", "ALLOWLISTED", None, (), "mega1_internal_helper", "Nested distance check helper."),
    Mega1TraceableDerivation("market_context.py", 651, "_volume_profile_poc_vah_val", "DERIVED", None, ("market_state.py:build_market_state",), None, "Volume profile POC/VAH/VAL; no Schwab profile leaves."),
    Mega1TraceableDerivation("market_context.py", 702, "_vwap_bands", "DERIVED", None, ("market_state.py:build_market_state",), None, "VWAP sigma bands from OHLCV bars."),
    Mega1TraceableDerivation("market_context.py", 788, "fetch_price_levels", "REPLACED", "pricehistory.candles.*.datetime", (), None, "Skip candles missing datetime leaf (fail-closed; no .get(datetime,0))."),
    Mega1TraceableDerivation("market_data_adapter.py", 49, "NormalizedBar.to_dict", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Serializes NormalizedBar; fields already Schwab-mapped."),
    Mega1TraceableDerivation("market_data_adapter.py", 62, "normalize_bar", "REPLACED", "pricehistory.candles.*.datetime", (), None, "Fail-closed Schwab leaf read: pricehistory.candles.*.datetime."),
    Mega1TraceableDerivation("market_data_adapter.py", 77, "normalize_bar._f", "ALLOWLISTED", None, (), "mega1_internal_helper", "Nested float parse inside normalize_bar; covered by parent REPLACED."),
    Mega1TraceableDerivation("market_data_adapter.py", 86, "normalize_bar._volume", "ALLOWLISTED", None, (), "mega1_internal_helper", "Nested volume parse inside normalize_bar; covered by parent REPLACED."),
    Mega1TraceableDerivation("market_data_adapter.py", 139, "normalize_bars", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Batch normalize_bar."),
    Mega1TraceableDerivation("market_data_adapter.py", 154, "schwab_candles_to_bars", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Schwab JSON candles → normalized bars + _ts."),
    Mega1TraceableDerivation("market_state.py", 35, "is_bias_actionable", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_state.py", 44, "derive_zone", "DERIVED", None, ("market_state.py:build_market_state",), None, "Regime taxonomy from bias_signal + net_delta."),
    Mega1TraceableDerivation("market_state.py", 81, "bias_color", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_state.py", 88, "pin_color", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_state.py", 95, "nd_color", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for nd_color output fields."),
    Mega1TraceableDerivation("market_state.py", 101, "zone_badge_color", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_state.py", 114, "dte_style", "NONE", None, (), None, "UI presentation helper; no market derivation."),
    Mega1TraceableDerivation("market_state.py", 497, "_f_ms", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("market_state.py", 503, "_oe_chain_row_snapshot", "SCHWAB_LEAF", "chains.callExpDateMap.*.openInterest", (), None, "Snapshots Schwab chain contract row fields."),
    Mega1TraceableDerivation("market_state.py", 554, "_oe_first_contract_row", "DERIVED", None, ("market_state.py:build_market_state",), None, "Composes Mega1 producers for _oe_first_contract_row output fields."),
    Mega1TraceableDerivation("market_state.py", 566, "_oe_composite_strike_row", "SCHWAB_LEAF", "chains.callExpDateMap.*.openInterest", (), None, "Aggregates call/put rows at strike from chain JSON."),
    Mega1TraceableDerivation("market_state.py", 635, "recommend_option_expression", "DERIVED", None, ("market_state.py:_oe_composite_strike_row", "market_state.py:_oe_chain_row_snapshot", "market_state.py:_oe_first_contract_row", "market_state.py:build_market_state",), None, "OE recommendation from chain fields."),
    Mega1TraceableDerivation("market_state.py", 794, "_oe_bid_ask_mid", "DERIVED", None, ("market_state.py:build_market_state",), None, "OP-006 mark-first mid ladder; bid/ask/2 only when mark+last absent."),
    Mega1TraceableDerivation("market_state.py", 852, "_schwab_days_to_expiration_for_contract", "SCHWAB_LEAF", "chains.*.daysToExpiration", (), None, "Reads Schwab DTE leaf when present."),
    Mega1TraceableDerivation("market_state.py", 878, "_build_contract_context_ms", "DERIVED", None, ("market_state.py:_schwab_days_to_expiration_for_contract", "market_state.py:_oe_bid_ask_mid",), None, "Composes Mega1 producers for _build_contract_context_ms output fields."),
    Mega1TraceableDerivation("market_state.py", 916, "build_market_state", "DERIVED", None, ("server.py:_build_rest_fast_quote_payload", "server.py:_fetch_state", "market_context.py:fetch_price_levels",), None, "Delegates to Schwab transport producers for build_market_state."),
    Mega1TraceableDerivation("math_snapshot_derive.py", 11, "derive_vwap_side", "DERIVED", None, ("market_context.py:fetch_price_levels", "market_state.py:build_market_state",), None, "spot vs vwap side; no Schwab vwap_side leaf."),
    Mega1TraceableDerivation("math_snapshot_derive.py", 28, "derive_pressure_trend", "DERIVED", None, ("market_state.py:build_market_state",), None, "DPI trend label; not a Schwab wire field."),
    Mega1TraceableDerivation("polling_adapter.py", 22, "_prev_trading_day", "ALLOWLISTED", None, (), "mega1_session_calendar", "Calendar helper for session window; no Schwab leaf."),
    Mega1TraceableDerivation("polling_adapter.py", 30, "fetch_bars_via_schwab_for_session", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Session-bounded pricehistory → schwab_candles_to_bars."),
    Mega1TraceableDerivation("polling_adapter.py", 69, "fetch_bars_via_schwab", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Day-period pricehistory → schwab_candles_to_bars."),
    Mega1TraceableDerivation("polling_adapter.py", 121, "poll_and_callback", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Poll loop delegates to fetch_bars_via_schwab."),
    Mega1TraceableDerivation("reauth_schwab.py", 30, "reauth", "NONE", None, (), None, "CLI OAuth reauth; no market-field reads."),
    Mega1TraceableDerivation("schwab_client.py", 30, "_schwab_oauth_scope", "NONE", None, (), None, "OAuth scope string from env; no market field."),
    Mega1TraceableDerivation("schwab_client.py", 35, "_get_auth_context_with_scope", "NONE", None, (), None, "No market-field derivation: OAuth authorize URL helper; transport only."),
    Mega1TraceableDerivation("schwab_client.py", 76, "_utc_ts", "NONE", None, (), None, "No market-field derivation: Diagnostic filename timestamp."),
    Mega1TraceableDerivation("schwab_client.py", 80, "ensure_dir", "NONE", None, (), None, "No market-field derivation in ensure_dir; Filesystem helper."),
    Mega1TraceableDerivation("schwab_client.py", 84, "save_diag", "NONE", None, (), None, "Writes diagnostic JSON; no market derivation."),
    Mega1TraceableDerivation("schwab_client.py", 93, "_resolve_token_path", "NONE", None, (), None, "No market-field derivation: Absolute token path normalization."),
    Mega1TraceableDerivation("schwab_client.py", 98, "inspect_token_file", "NONE", None, (), None, "No market-field derivation: Token metadata inspection; no quote fields."),
    Mega1TraceableDerivation("schwab_client.py", 168, "auth_is_refreshable", "NONE", None, (), None, "No market-field derivation: Token refresh capability check."),
    Mega1TraceableDerivation("schwab_client.py", 173, "build_client_from_token", "ALLOWLISTED", None, (), "mega1_schwab_py_client", "Constructs schwab-py client from token file."),
    Mega1TraceableDerivation("schwab_client.py", 230, "_parse_callback_port", "NONE", None, (), None, "No market-field derivation: OAuth callback port parse."),
    Mega1TraceableDerivation("schwab_client.py", 238, "_wait_for_callback_port", "NONE", None, (), None, "No market-field derivation: OAuth callback wait loop."),
    Mega1TraceableDerivation("schwab_client.py", 251, "run_login_flow", "NONE", None, (), None, "No market-field read or write in run_login_flow; transport or control flow only."),
    Mega1TraceableDerivation("schwab_client.py", 258, "run_login_flow._run", "NONE", None, (), None, "No market-field derivation: Nested helper inside run_login_flow; parent row owns derivation semantics."),
    Mega1TraceableDerivation("schwab_client.py", 301, "run_manual_flow", "NONE", None, (), None, "No market-field derivation: Manual OAuth URL flow."),
    Mega1TraceableDerivation("schwab_client.py", 324, "_is_token_error", "NONE", None, (), None, "No market-field derivation: Classifies auth errors for retry."),
    Mega1TraceableDerivation("schwab_client.py", 337, "safe_get_quote", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Schwab get_quote wrapper; returns raw quote JSON."),
    Mega1TraceableDerivation("schwab_client.py", 381, "safe_get_price_history", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Schwab price history wrapper; candles passed downstream."),
    Mega1TraceableDerivation("schwab_client.py", 421, "safe_get_chain", "SCHWAB_LEAF", "chains.callExpDateMap.*.openInterest", (), None, "Schwab option chain wrapper."),
    Mega1TraceableDerivation("server.py", 147, "_log_schwab_startup_diagnostics", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_log_schwab_startup_diagnostics)."),
    Mega1TraceableDerivation("server.py", 187, "reset_schwab_client", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (reset_schwab_client)."),
    Mega1TraceableDerivation("server.py", 194, "get_client", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_client)."),
    Mega1TraceableDerivation("server.py", 213, "_safe_get_quote_with_retry", "DERIVED", None, ("schwab_client.py:safe_get_quote",), None, "Schwab get_quote wrapper with token retry."),
    Mega1TraceableDerivation("server.py", 241, "_snapshot_throttle_enabled", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 246, "_snapshot_row_insert_allowed", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 255, "_snapshot_row_insert_committed", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 309, "_l1_sse_remote_key", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 319, "_l1_light_sse_count_by_scope", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 328, "_l1_light_sse_try_reserve", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 389, "_l1_light_sse_release", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 403, "_l1_round_floats_for_json", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 416, "_l1_material_dict_for_fingerprint", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 427, "_l1_payload_fingerprint", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 434, "_l1_record_payload_identity", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 448, "_l1_put_l1_client_queue", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 471, "_l1_put_thread_queue_notify", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 510, "_get_fast_quote_executor", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_get_fast_quote_executor)."),
    Mega1TraceableDerivation("server.py", 520, "_get_db_fill_outcomes_executor", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 539, "_tier_c_inflight_key", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 544, "_analytics_generated_ts", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 548, "_attach_analytics_freshness_contract", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 586, "_schedule_analytics_recompute", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 602, "_schedule_analytics_recompute._work", "NONE", None, (), None, "No market-field derivation: Nested helper inside _schedule_analytics_recompute; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 626, "_stamp_analytics_freshness_on_completed_fetch", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 657, "_any_sse_viewer_for_ticker", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 663, "_minimal_analytics_pending_dict", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 683, "_sse_viewer_cache_ttl", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 694, "_evict_old_expiry_entries", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 704, "_build_rest_fast_quote_payload", "DERIVED", None, ("schwab_client.py:safe_get_quote",), None, "Fail-closed Schwab leaf read: quotes.quote.mark."),
    Mega1TraceableDerivation("server.py", 720, "_build_rest_fast_quote_payload._attempt_hook", "NONE", None, (), None, "No market-field derivation: Nested helper inside _build_rest_fast_quote_payload; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 833, "_fetch_fast_quote_payload", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_fetch_fast_quote_payload)."),
    Mega1TraceableDerivation("server.py", 869, "_broadcast_snapshot", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 905, "_get_prediction_override", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 919, "_latest_cached_ms_and_key_for_ticker", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 939, "_stream_spot_and_of_regime", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_stream_spot_and_of_regime)."),
    Mega1TraceableDerivation("server.py", 983, "_on_tick_broadcast_sync", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_on_tick_broadcast_sync)."),
    Mega1TraceableDerivation("server.py", 1084, "_CandleAccumulator.__init__", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_CandleAccumulator.__init__)."),
    Mega1TraceableDerivation("server.py", 1092, "_CandleAccumulator._bar_start", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1096, "_CandleAccumulator.tick", "DERIVED", None, ("server.py:_CandleAccumulator.seed", "schwab_client.py:safe_get_quote",), None, "Poll-synthesized OHLCV from spot ticks + totalVolume delta."),
    Mega1TraceableDerivation("server.py", 1156, "_CandleAccumulator.get_bars", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_CandleAccumulator.get_bars)."),
    Mega1TraceableDerivation("server.py", 1160, "_CandleAccumulator.get_bars_source", "DERIVED", None, ("server.py:_fetch_state",), None, "Bar provenance label for VWAP path."),
    Mega1TraceableDerivation("server.py", 1164, "_CandleAccumulator.seed", "SCHWAB_LEAF", "pricehistory.candles.*.datetime", (), None, "Seeds from Schwab pricehistory candles; datetime required."),
    Mega1TraceableDerivation("server.py", 1201, "_CandleAccumulator.has_bars", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1215, "_IVTracker.__init__", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1219, "_IVTracker.tick", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1227, "_IVTracker.direction", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1252, "_VIXTracker.__init__", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1256, "_VIXTracker.tick", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1270, "_VIXTracker.direction", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1274, "_VIXTracker.vs_prev", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_VIXTracker.vs_prev)."),
    Mega1TraceableDerivation("server.py", 1323, "_market_context_panel_auto_candidates", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_market_context_panel_auto_candidates)."),
    Mega1TraceableDerivation("server.py", 1329, "_sync_market_context_panel_into_logging_universe", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_sync_market_context_panel_into_logging_universe)."),
    Mega1TraceableDerivation("server.py", 1343, "_logging_universe_fifo_eviction_enabled", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1352, "_max_user_persisted_cap_resolved", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1367, "_user_persisted_enrollment_policy", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1381, "_run_legacy_logger_json_migration", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1397, "_load_persisted_tickers", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_load_persisted_tickers)."),
    Mega1TraceableDerivation("server.py", 1457, "_hydrate_logger_tickers_from_db", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_hydrate_logger_tickers_from_db)."),
    Mega1TraceableDerivation("server.py", 1503, "_is_loggable_session", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_is_loggable_session)."),
    Mega1TraceableDerivation("server.py", 1520, "_add_logger_ticker", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1603, "_register_tracked_ticker", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1622, "_get_mkt_ctx", "DERIVED", None, ("market_context.py:fetch_market_context",), None, "Schwab API wrapper or wire JSON ingest path."),
    Mega1TraceableDerivation("server.py", 1669, "_logger_fetch_and_log", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_logger_fetch_and_log)."),
    Mega1TraceableDerivation("server.py", 1715, "_logger_loop", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_logger_loop)."),
    Mega1TraceableDerivation("server.py", 1768, "start_logger", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1778, "stop_logger", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1786, "_jsonable", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1797, "_ms_to_dict", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_ms_to_dict)."),
    Mega1TraceableDerivation("server.py", 1844, "_strip_trader_hidden_horizon_keys", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1861, "_strip_trader_hidden_horizon_keys._scrub_mapping", "NONE", None, (), None, "No market-field derivation: Nested helper inside _strip_trader_hidden_horizon_keys; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 1878, "_apply_trader_horizon_contract", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 1898, "_attach_stack_runtime_and_governance", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_attach_stack_runtime_and_governance)."),
    Mega1TraceableDerivation("server.py", 1988, "_attach_stack_runtime_and_governance._tri", "NONE", None, (), None, "No market-field derivation: Nested helper inside _attach_stack_runtime_and_governance; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 2077, "_trader_accuracy_subset", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2087, "_expiries_from_contracts", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2098, "_filter_contracts_by_selected_expiry", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_filter_contracts_by_selected_expiry)."),
    Mega1TraceableDerivation("server.py", 2118, "_kl_expiry_source_label", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_kl_expiry_source_label)."),
    Mega1TraceableDerivation("server.py", 2130, "_selected_schwab_days_to_expiration", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_selected_schwab_days_to_expiration)."),
    Mega1TraceableDerivation("server.py", 2173, "_snapshot_expiry_hours_from_schwab_dte", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_snapshot_expiry_hours_from_schwab_dte)."),
    Mega1TraceableDerivation("server.py", 2188, "_fetch_expiries_light", "DERIVED", None, ("schwab_client.py:safe_get_chain",), None, "Schwab API wrapper or wire JSON ingest path."),
    Mega1TraceableDerivation("server.py", 2222, "_default_expiry", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2244, "_safe_float_quote", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_safe_float_quote)."),
    Mega1TraceableDerivation("server.py", 2254, "_update_rest_cum_delta", "DERIVED", None, ("server.py:_safe_float_quote",), None, "REST tape proxy when stream unavailable."),
    Mega1TraceableDerivation("server.py", 2293, "_compute_vwap_from_bars", "DERIVED", None, ("server.py:_fetch_state",), None, "Typical-price VWAP; no Schwab VWAP leaf."),
    Mega1TraceableDerivation("server.py", 2362, "_l1_generation_pop", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2369, "_l1_next_generation", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_next_generation)."),
    Mega1TraceableDerivation("server.py", 2395, "_l1_touch_scope", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_touch_scope)."),
    Mega1TraceableDerivation("server.py", 2403, "_l1_remove_scope", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2407, "_l1_after_scope_row_dropped", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2414, "_l1_cache_maintain", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2449, "_l1_attach_freshness_semantics", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_attach_freshness_semantics)."),
    Mega1TraceableDerivation("server.py", 2475, "_l1_sync_of_probe_cache_from_authoritative_build", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_sync_of_probe_cache_from_authoritative_build)."),
    Mega1TraceableDerivation("server.py", 2487, "_l1_quote_hook_order_flow_signature", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_quote_hook_order_flow_signature)."),
    Mega1TraceableDerivation("server.py", 2534, "_resolve_l2_cache_entry_for_l1", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2550, "_l2_refresh_in_progress_for_l1", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2561, "_project_l1", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_project_l1)."),
    Mega1TraceableDerivation("server.py", 2622, "_l1_adaptive_materiality_context", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_adaptive_materiality_context)."),
    Mega1TraceableDerivation("server.py", 2662, "_l1_maybe_rebuild_quote_scope", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_maybe_rebuild_quote_scope)."),
    Mega1TraceableDerivation("server.py", 2692, "_l1_on_quote_updated", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_on_quote_updated)."),
    Mega1TraceableDerivation("server.py", 2704, "_l1_on_l2_snapshot_ready", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2709, "_l1_http_get_projection", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_l1_http_get_projection)."),
    Mega1TraceableDerivation("server.py", 2758, "_l1_scope_key", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2763, "_l1_notify_sse_after_authoritative_build", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2796, "_l1_light_sse_dispatch_loop", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2810, "_l1_light_sse_dispatch_loop._blocking_get", "NONE", None, (), None, "No market-field derivation: Nested helper inside _l1_light_sse_dispatch_loop; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 2830, "_latest_cache_entry_for_ticker", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 2851, "_tier_a_live_state_dict", "DERIVED", None, ("server.py:_fetch_state",), None, "Schwab API wrapper or wire JSON ingest path."),
    Mega1TraceableDerivation("server.py", 3046, "_fetch_state", "DERIVED", None, ("schwab_client.py:safe_get_quote", "schwab_client.py:safe_get_chain", "schwab_client.py:safe_get_price_history",), None, "Day 1.5: spread_frac mark-denom only; composes quote+chain+pricehistory via schwab_client."),
    Mega1TraceableDerivation("server.py", 3637, "_fetch_state._bucket_total_oi", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 4739, "_fetch_state._fv", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 4755, "_fetch_state._fs", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 4763, "_fetch_state._foi", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 5040, "_fetch_state._sync_missing_binaries_to_active", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 5092, "_fetch_state._model_status_from_artifact", "NONE", None, (), None, "No market-field derivation: Nested helper inside _fetch_state; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 5291, "_app_lifespan", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_app_lifespan)."),
    Mega1TraceableDerivation("server.py", 5456, "root", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5471, "favicon", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5477, "guide_data_stewardship", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5515, "guide_training_and_maintenance", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5557, "guide_pipeline_quality", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5600, "ops_panel", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5609, "api_ops_status", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5623, "api_ops_run", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5654, "governance_visibility_page", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5663, "api_governance_panel", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5689, "api_governance_manual_promote", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5749, "api_governance_manual_rollback", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5809, "api_ops_run_sequence", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 5842, "_tier_c_analytics_json_response", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_tier_c_analytics_json_response)."),
    Mega1TraceableDerivation("server.py", 5946, "get_live_state", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_live_state)."),
    Mega1TraceableDerivation("server.py", 5960, "get_analytics_light", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_analytics_light)."),
    Mega1TraceableDerivation("server.py", 5980, "get_analytics_light_stream", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_analytics_light_stream)."),
    Mega1TraceableDerivation("server.py", 5995, "get_analytics_light_stream.event_generator", "NONE", None, (), None, "No market-field derivation: Nested helper inside get_analytics_light_stream; parent row owns derivation semantics."),
    Mega1TraceableDerivation("server.py", 6018, "get_analytics_state", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_analytics_state)."),
    Mega1TraceableDerivation("server.py", 6031, "get_state", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6044, "api_live_plane", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (api_live_plane)."),
    Mega1TraceableDerivation("server.py", 6070, "post_streaming_active_ticker", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (post_streaming_active_ticker)."),
    Mega1TraceableDerivation("server.py", 6086, "_l1_sse_light_diag_payload", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6136, "get_l1_diagnostics", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_l1_diagnostics)."),
    Mega1TraceableDerivation("server.py", 6248, "post_ticker_switch_diagnostics", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6257, "get_ticker_switch_diagnostics", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6265, "fast_quote", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (fast_quote)."),
    Mega1TraceableDerivation("server.py", 6316, "sse_stream", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (sse_stream)."),
    Mega1TraceableDerivation("server.py", 6333, "sse_stream.event_generator", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (sse_stream.event_generator)."),
    Mega1TraceableDerivation("server.py", 6383, "_broadcast_live_quote_sse_payloads", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_broadcast_live_quote_sse_payloads)."),
    Mega1TraceableDerivation("server.py", 6417, "_sse_live_quote_loop", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_sse_live_quote_loop)."),
    Mega1TraceableDerivation("server.py", 6427, "_sse_background_loop", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_sse_background_loop)."),
    Mega1TraceableDerivation("server.py", 6466, "get_expiries", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6485, "logger_status", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (logger_status)."),
    Mega1TraceableDerivation("server.py", 6551, "logger_universe", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (logger_universe)."),
    Mega1TraceableDerivation("server.py", 6586, "logger_universe_by_category", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6606, "logger_pin", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6636, "logger_unpin", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6651, "logger_add", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6663, "logger_remove", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (logger_remove)."),
    Mega1TraceableDerivation("server.py", 6701, "prediction_override", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6714, "prediction_override_clear", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6725, "health", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 6733, "get_price_levels", "SCHWAB_LEAF", "quotes.quote.lastPrice", (), None, "Schwab API wrapper or wire JSON ingest path."),
    Mega1TraceableDerivation("server.py", 6746, "_build_raw_levels_used", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_build_raw_levels_used)."),
    Mega1TraceableDerivation("server.py", 6783, "_liquidity_live_1m_overlay_bars", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_liquidity_live_1m_overlay_bars)."),
    Mega1TraceableDerivation("server.py", 6810, "_liquidity_spot_from_cache_any_expiry", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_liquidity_spot_from_cache_any_expiry)."),
    Mega1TraceableDerivation("server.py", 6829, "_liquidity_fusion_from_cache", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_liquidity_fusion_from_cache)."),
    Mega1TraceableDerivation("server.py", 6877, "_liquidity_zone_tradeable_fields", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (_liquidity_zone_tradeable_fields)."),
    Mega1TraceableDerivation("server.py", 6909, "get_liquidity_snapshot", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_liquidity_snapshot)."),
    Mega1TraceableDerivation("server.py", 7057, "get_liquidity_playbook_state", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (get_liquidity_playbook_state)."),
    Mega1TraceableDerivation("server.py", 7096, "debug_charm", "DERIVED", None, ("schwab_client.py:safe_get_chain",), None, "Schwab API wrapper or wire JSON ingest path."),
    Mega1TraceableDerivation("server.py", 7218, "get_accuracy", "NONE", None, (), None, "No market-field derivation: No Schwab market-field derivation in function body."),
    Mega1TraceableDerivation("server.py", 7259, "debug_prediction", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (debug_prediction)."),
    Mega1TraceableDerivation("snapshot_access.py", 31, "require_snapshot_timeframe", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Enforces explicit timeframe on snapshot SQL reads."),
    Mega1TraceableDerivation("snapshot_access.py", 50, "is_canonical_timeframe", "NONE", None, (), None, "No market-field derivation: Compares to CANONICAL_TIMEFRAME constant."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 54, "_connect", "NONE", None, (), None, "No market-field derivation: SQLite connection helper."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 66, "_minute_bucket", "ALLOWLISTED", None, (), "mega1_internal_helper", "int(ts_utc//60) bucket key."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 71, "_safe_float", "NONE", None, (), None, "No market-field derivation in _safe_float; Parse helper."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 80, "resample_to_1m", "DERIVED", None, ("snapshot_normalizer.py:fetch_rows_for_normalization",), None, "Synthetic 1m from sub-minute rows; spot proxies tagged in missing_fields."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 217, "fetch_raw_subminute_rows", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (fetch_raw_subminute_rows)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 228, "resolve_source_timeframe", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (resolve_source_timeframe)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 243, "fetch_rows_for_normalization", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (fetch_rows_for_normalization)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 255, "normalize_ticker", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (normalize_ticker)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 266, "_normalized_table_exists", "NONE", None, (), None, "No market-field derivation in _normalized_table_exists; Schema guard."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 273, "_get_snapshots_columns", "NONE", None, (), None, "No market-field derivation in _get_snapshots_columns; PRAGMA column list."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 279, "_table_column_set", "NONE", None, (), None, "No market-field derivation: PRAGMA table columns."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 284, "_normalized_insert_columns", "NONE", None, (), None, "No market-field derivation: INSERT column alignment."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 299, "materialize_normalized_table", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (materialize_normalized_table)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 386, "clear_normalized_table", "NONE", None, (), None, "No market-field derivation in clear_normalized_table; DELETE helper."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 397, "validate_normalization", "NONE", None, (), None, "No market-field derivation: DB integrity checks on normalized table."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 492, "load_normalized_rows", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows, not Schwab wire JSON (load_normalized_rows)."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 517, "run_full_materialization", "NONE", None, (), None, "No market-field derivation: CLI orchestration materialize+validate."),
    Mega1TraceableDerivation("snapshot_normalizer.py", 539, "_print_ingestion_context", "NONE", None, (), None, "No market-field derivation: Diagnostic print helper."),
    Mega1TraceableDerivation("sse_adapter.py", 24, "SSEBarStream.connect", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("sse_adapter.py", 29, "SSEBarStream.disconnect", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("sse_adapter.py", 34, "SSEBarStream.set_bar_callback", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("sse_adapter.py", 39, "SSEBarStream.is_connected", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("sse_adapter.py", 43, "sse_bars_stub", "NONE", None, (), None, "No market-field derivation: Unimplemented transport stub."),
    Mega1TraceableDerivation("websocket_adapter.py", 24, "WebSocketBarStream.connect", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("websocket_adapter.py", 29, "WebSocketBarStream.disconnect", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("websocket_adapter.py", 34, "WebSocketBarStream.set_bar_callback", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("websocket_adapter.py", 39, "WebSocketBarStream.is_connected", "NONE", None, (), None, "No market-field derivation: Abstract transport contract; no Schwab read."),
    Mega1TraceableDerivation("websocket_adapter.py", 44, "websocket_bars_stub", "NONE", None, (), None, "No market-field derivation: Unimplemented transport stub."),
    # ── big-audit inventory sync (functions added to production since last inventory pass) ──
    Mega1TraceableDerivation("market_state.py", 505, "_ms_price_disp", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Display formatter helper for persisted ms_dict price fields; no Schwab wire derivation (_ms_price_disp)."),
    Mega1TraceableDerivation("server.py", 550, "_invalidate_analytics_cache_after_bg_failures", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Internal analytics cache invalidation helper / no Schwab wire derivation (_invalidate_analytics_cache_after_bg_failures)."),
    Mega1TraceableDerivation("server.py", 584, "_reset_analytics_bg_fail_count", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Internal background-failure counter reset helper (_reset_analytics_bg_fail_count)."),
    Mega1TraceableDerivation("server.py", 588, "_record_analytics_bg_failure", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Internal background-failure counter increment helper (_record_analytics_bg_failure)."),
    Mega1TraceableDerivation("server.py", 1911, "_filter_horizon_prob_bars_primary_only", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Reads persisted snapshot SQLite rows / horizon filter helper, not Schwab wire JSON (_filter_horizon_prob_bars_primary_only)."),
    Mega1TraceableDerivation("server.py", 2295, "_parse_quote_node_session_fields", "ALLOWLISTED", None, (), "mega1_sqlite_internal", "Parses persisted quote-node session fields; not Schwab wire JSON (_parse_quote_node_session_fields)."),
)

