"""The root population under the root rule (governance/provenance_inventory.py, RC-532).

ROUTES — every served route, classified (an unclassified route fails the suite).
MARKET_STATE — every MarketState field: (category, producer row ref or None = OPEN).
ENGINE_INPUTS — every argument of every decision-engine entry: producer row ref or None.

Categories are reviewed human judgment from the closed vocabulary FIELD_CATEGORIES; the
producer refs were seeded mechanically from build_market_state's assignments (2026-09-07)
and are OPEN where the assembler takes the value from a local the seed could not trace.
An OPEN root is NOT_PROVEN, listed by name, and reported — never hidden.
"""
from __future__ import annotations

ROUTES: dict[str, tuple[str, str | None]] = {
    '/': ('PAGE', None),
    '/api/accuracy': ('CARRIER', None),
    '/api/analytics/light': ('CARRIER', None),
    '/api/analytics/light/stream': ('STREAM', None),
    '/api/analytics/state': ('CARRIER', None),
    '/api/analytics/warm': ('OPERATOR_INPUT', None),
    '/api/bars1m': ('PRODUCER', 'server.py:get_bars1m'),
    '/api/build': ('OPS', None),
    '/api/chain': ('PRODUCER', 'server.py:get_chain'),
    '/api/debug/charm': ('DIAGNOSTIC', None),
    '/api/debug/prediction': ('DIAGNOSTIC', None),
    '/api/decision/{decision_id}': ('CARRIER', None),
    '/api/desk/brief': ('CARRIER', None),
    '/api/desk/dossier': ('CARRIER', None),
    '/api/desk/evidence': ('CARRIER', None),
    '/api/desk/materialize': ('OPERATOR_INPUT', None),
    '/api/desk/radar': ('CARRIER', None),
    '/api/desk/structure': ('CARRIER', None),
    '/api/diagnostics/chain-gate': ('DIAGNOSTIC', None),
    '/api/diagnostics/l1': ('DIAGNOSTIC', None),
    '/api/diagnostics/sqlite-contention': ('DIAGNOSTIC', None),
    '/api/diagnostics/terrain-producer': ('DIAGNOSTIC', None),
    '/api/diagnostics/ticker-switch': ('DIAGNOSTIC', None),
    '/api/expiries': ('PRODUCER', None),
    '/api/exposure/book': ('PRODUCER', 'server.py:get_exposure_book'),
    '/api/exposure/flow': ('PRODUCER', 'server.py:get_exposure_flow'),
    '/api/exposure/history': ('PRODUCER', 'server.py:get_exposure_history'),
    '/api/fast-quote': ('PRODUCER', 'server.py:fast_quote'),
    '/api/forces': ('PRODUCER', 'server.py:get_forces'),
    '/api/governance/manual-promote': ('GOVERNANCE', None),
    '/api/governance/manual-rollback': ('GOVERNANCE', None),
    '/api/governance/panel': ('GOVERNANCE', None),
    '/api/health': ('OPS', None),
    '/api/internal/reload_models': ('OPS', None),
    '/api/level_crosses': ('CARRIER', None),
    '/api/levels': ('PRODUCER', 'server.py:get_levels'),
    '/api/liquidity-playbook-state': ('CARRIER', None),
    '/api/liquidity-snapshot': ('CARRIER', None),
    '/api/live/plane': ('PRODUCER', 'server.py:api_live_plane'),
    '/api/live/state': ('CARRIER', None),
    '/api/logger/add': ('LOGGER', None),
    '/api/logger/pin': ('LOGGER', None),
    '/api/logger/remove': ('LOGGER', None),
    '/api/logger/status': ('LOGGER', None),
    '/api/logger/universe': ('LOGGER', None),
    '/api/logger/universe/by-category': ('LOGGER', None),
    '/api/logger/unpin': ('LOGGER', None),
    '/api/ops/calibration_rowcount': ('OPS', None),
    '/api/ops/run': ('OPS', None),
    '/api/ops/run-sequence': ('OPS', None),
    '/api/ops/status': ('OPS', None),
    '/api/order-flow/microstructure': ('PRODUCER', 'server.py:api_order_flow_microstructure'),
    '/api/order-flow/options-microstructure': ('PRODUCER', 'server.py:api_order_flow_options_microstructure'),
    '/api/prediction/override': ('OPERATOR_INPUT', None),
    '/api/prediction/override/clear': ('OPERATOR_INPUT', None),
    '/api/price-levels': ('PRODUCER', 'server.py:get_price_levels'),
    '/api/release/current': ('OPS', None),
    '/api/spot': ('PRODUCER', 'server.py:get_spot'),
    '/api/state': ('CARRIER', None),
    '/api/stream': ('STREAM', None),
    '/api/streaming/active-option-contract': ('OPERATOR_INPUT', None),
    '/api/streaming/active-ticker': ('OPERATOR_INPUT', None),
    '/api/terrain': ('PRODUCER', 'server.py:get_terrain'),
    '/api/terrain/quarantine/release': ('GOVERNANCE', None),
    '/api/terrain/radar': ('PRODUCER', 'server.py:get_terrain_radar'),
    '/api/terrain/scorecard': ('PRODUCER', None),
    '/api/terrain/strikes': ('PRODUCER', 'server.py:get_terrain_strikes'),
    '/api/vol-observability': ('DIAGNOSTIC', None),
    '/chart': ('PAGE', None),
    '/desk': ('PAGE', None),
    '/exposure': ('PAGE', None),
    '/favicon.ico': ('PAGE', None),
    '/governance': ('PAGE', None),
    '/guide/data-stewardship': ('PAGE', None),
    '/guide/pipeline-quality': ('PAGE', None),
    '/guide/training-and-maintenance': ('PAGE', None),
    '/ops': ('PAGE', None),
    '/options': ('PAGE', None),
}

MARKET_STATE: dict[str, tuple[str, str | None]] = {
    'ticker': ('IDENTITY', None),
    'selected_exp': ('IDENTITY', None),
    'session_label': ('PRESENTATION', None),
    'spot': ('MARKET', None),
    'bid': ('MARKET', None),
    'ask': ('MARKET', None),
    'spot_disp': ('PRESENTATION', None),
    'bid_disp': ('PRESENTATION', None),
    'ask_disp': ('PRESENTATION', None),
    'bias_signal': ('DECISION', None),
    'pin_strength': ('MARKET', None),
    'net_delta': ('MARKET', 'market_data_adapter.py:normalize_bar._f'),
    'net_gamma': ('MARKET', 'market_data_adapter.py:normalize_bar._f'),
    'gex_magnitude': ('MARKET', 'math_exposure_core.py:gex_magnitude_label'),
    'dex_magnitude': ('MARKET', None),
    'zone': ('MARKET', 'market_state.py:derive_zone'),
    'bias_color_css': ('PRESENTATION', None),
    'pin_color_css': ('PRESENTATION', None),
    'nd_color_css': ('PRESENTATION', 'market_state.py:nd_color'),
    'nd_disp': ('PRESENTATION', None),
    'vix': ('MARKET', None),
    'vix_regime': ('CONTROL', None),
    'vix_color': ('PRESENTATION', None),
    'vix_implication': ('MARKET', None),
    'pcr_val': ('MARKET', 'market_data_adapter.py:normalize_bar._f'),
    'pcr_arrow': ('PRESENTATION', None),
    'pcr_color': ('PRESENTATION', None),
    'pcr_label': ('PRESENTATION', None),
    'iv_direction': ('DECISION', None),
    'bias_resolved': ('DECISION', None),
    'nd_resolved': ('MARKET', None),
    'rec_strike': ('DECISION', None),
    'rec_side': ('DECISION', None),
    'call_option_expiry': ('IDENTITY', None),
    'call_option_right': ('IDENTITY', None),
    'is_no_trade': ('CONTROL', None),
    'dte_warn': ('CONTROL', None),
    'dte_color': ('PRESENTATION', None),
    'liq_ok': ('CONTROL', 'math_probabilities.py:score_option_expression'),
    'ratio': ('MARKET', 'math_probabilities.py:score_option_expression'),
    'vol_oi': ('MARKET', 'math_probabilities.py:score_option_expression'),
    'spread': ('MARKET', 'math_probabilities.py:score_option_expression'),
    'entry_zone_lo': ('DECISION', None),
    'entry_zone_hi': ('DECISION', None),
    'entry_zone_str': ('PRESENTATION', None),
    'rules_signal': ('DECISION', None),
    'rules_conviction': ('DECISION', None),
    'zone_label': ('PRESENTATION', None),
    'zone_badge_css': ('PRESENTATION', None),
    'rules_headline': ('PRESENTATION', None),
    'rules_headline_1m': ('PRESENTATION', None),
    'rules_detail': ('MARKET', None),
    'rules_alerts': ('MARKET', None),
    'session_high': ('CONTROL', None),
    'session_low': ('CONTROL', None),
    'last_sweep_type': ('MARKET', None),
    'last_sweep_level': ('MARKET', None),
    'last_sweep_held': ('MARKET', None),
    'n_sweeps_today': ('MARKET', None),
    'validation_passed': ('MARKET', None),
    'structure_valid': ('CONTROL', None),
    'probability_valid': ('CONTROL', None),
    'risk_valid': ('CONTROL', None),
    'validation_summary': ('PRESENTATION', None),
    'r_units': ('MARKET', None),
    'execution_mode': ('CONTROL', None),
    'sizing_summary': ('PRESENTATION', None),
    'call_signal': ('DECISION', None),
    'call_conviction': ('DECISION', None),
    'entry': ('DECISION', None),
    'stop': ('DECISION', None),
    'target': ('DECISION', None),
    'target2': ('DECISION', None),
    'reward_risk': ('DECISION', None),
    'reward_risk2': ('DECISION', None),
    'entry_disp': ('PRESENTATION', None),
    'stop_disp': ('PRESENTATION', None),
    'target_disp': ('PRESENTATION', None),
    'target2_disp': ('PRESENTATION', None),
    'rr_disp': ('PRESENTATION', None),
    'rr2_disp': ('PRESENTATION', None),
    'call_headline': ('PRESENTATION', None),
    'call_reasoning': ('CONTROL', None),
    'trade_type': ('MARKET', None),
    'trade_type_label': ('PRESENTATION', None),
    'invalidation': ('MARKET', None),
    'confluence_count': ('DEBUG', None),
    'confluence_total': ('MARKET', None),
    'confluence_detail': ('MARKET', None),
    'mh_promoted_directional': ('DECISION', None),
    'time_qualifier': ('MARKET', None),
    'replay_max_hold_bars': ('MARKET', None),
    'size_cue': ('DECISION', None),
    'rules_pred_agree': ('DECISION', None),
    'time_warning': ('CONTROL', None),
    'size_note': ('PRESENTATION', None),
    'contract_context': ('MARKET', 'market_state.py:_build_contract_context_ms'),
    'event_risk_level': ('DECISION', None),
    'event_risk_detail': ('DECISION', None),
    'call_readiness_score': ('DECISION', None),
    'call_state': ('CONTROL', None),
    'call_forecast_state': ('CONTROL', None),
    'call_readiness_reasons': ('CONTROL', None),
    'call_missing_conditions': ('DECISION', None),
    'call_readiness_component_scores': ('DECISION', None),
    'call_wait_blocker': ('CONTROL', None),
    'put_readiness_score': ('DECISION', None),
    'put_state': ('CONTROL', None),
    'put_forecast_state': ('CONTROL', None),
    'put_readiness_reasons': ('CONTROL', None),
    'put_missing_conditions': ('MARKET', None),
    'put_readiness_component_scores': ('DECISION', None),
    'final_bias': ('DECISION', None),
    'final_confidence': ('DECISION', None),
    'final_quality': ('MARKET', None),
    'final_tradeable': ('DECISION', None),
    'primary_horizon': ('DECISION', None),
    'trade_mode': ('CONTROL', None),
    'alignment_state_display': ('PRESENTATION', None),
    'conflict_level_display': ('PRESENTATION', None),
    'contradiction_state': ('CONTROL', None),
    'supporting_horizon_summary': ('PRESENTATION', None),
    'entry_state': ('CONTROL', None),
    'entry_display_text': ('PRESENTATION', None),
    'stop_display_text': ('PRESENTATION', None),
    'targets_display': ('PRESENTATION', None),
    'hold_style': ('PRESENTATION', None),
    'size_modifier_display': ('PRESENTATION', None),
    'risk_note': ('PRESENTATION', None),
    'wait_reason': ('CONTROL', None),
    'decision_provenance': ('MARKET', None),
    'mhap_rows': ('DECISION', None),
    'guest_anchor_active': ('MARKET', None),
    'guest_anchor_weights_ticker': ('MARKET', None),
    'guest_anchor_affiliation': ('MARKET', None),
    'guest_anchor_rationale': ('MARKET', None),
    'model_serving_provenance_v1': ('DECISION', None),
    'mhap_legend': ('DECISION', None),
    'horizon_prob_bars': ('DECISION', None),
    'eval_accuracy_oos': ('MARKET', None),
    'eval_log_loss_oos': ('MARKET', None),
    'eval_pnl_realized_contract_oos': ('MARKET', None),
    'eval_realized_contract_metrics_oos': ('MARKET', None),
    'pred_headline': ('PRESENTATION', None),
    'up_prob_1c': ('DECISION', None),
    'down_prob_1c': ('DECISION', None),
    'flat_prob_1c': ('DECISION', None),
    'up_prob_5c': ('DECISION', None),
    'down_prob_5c': ('DECISION', None),
    'flat_prob_5c': ('DECISION', None),
    'up_prob_15c': ('DECISION', None),
    'down_prob_15c': ('DECISION', None),
    'flat_prob_15c': ('DECISION', None),
    'up_prob_60c': ('DECISION', None),
    'down_prob_60c': ('DECISION', None),
    'flat_prob_60c': ('DECISION', None),
    'pred_dominant_by_horizon': ('DECISION', None),
    'movement_head_probs': ('DECISION', None),
    'fusion_policy_snapshot_cols': ('CONTROL', None),
    'dominant_dir': ('MARKET', None),
    'dominant_prob': ('DECISION', None),
    'confidence': ('DECISION', None),
    'historical_5c_dominant_dir': ('MARKET', None),
    'historical_5c_dominant_prob': ('DECISION', None),
    'empirical_confidence': ('DECISION', None),
    'forward_prob_up': ('DECISION', None),
    'forward_prob_down': ('DECISION', None),
    'forward_prob_flat': ('DECISION', None),
    'forward_provenance': ('MARKET', None),
    'canonical_provenance': ('MARKET', None),
    'samples_used': ('MARKET', None),
    'model_note': ('PRESENTATION', None),
    'model_version': ('DEBUG', None),
    'pred_model_source': ('DECISION', None),
    'mh_prob_source_by_horizon': ('DECISION', None),
    'horizon_directional_authorized': ('DECISION', None),
    'horizon_directional_authorization_reason': ('CONTROL', None),
    'horizon_fusion_available': ('DECISION', None),
    'pred_override_source': ('CONTROL', None),
    'timeframe_reads': ('MARKET', None),
    'avg_5c_pts': ('MARKET', None),
    'avg_15c_pts': ('MARKET', None),
    'avg_60c_pts': ('MARKET', None),
    'reversal_risk': ('DECISION', None),
    'reversal_label': ('PRESENTATION', None),
    'reversal_shortfall': ('DECISION', None),
    'reversal_severity': ('DECISION', None),
    'vol_regime': ('CONTROL', None),
    'vol_regime_summary': ('PRESENTATION', None),
    'vol_regime_conviction_mult': ('CONTROL', None),
    'vol_regime_risk_mult': ('CONTROL', None),
    'order_flow_score': ('DECISION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_direction': ('DECISION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_regime': ('CONTROL', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_readiness': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'book_imbalance_5': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'cum_delta_proxy': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'tape_pressure_30s': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'options_flow_score': ('DECISION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'institutional_flow_proxy_score': ('DECISION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_verdict': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_verdict_color': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_arrow': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_agreement': ('MARKET', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_score_arrow': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_score_label': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_book_arrow': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_book_label': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_delta_arrow': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_opt_arrow': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'order_flow_opt_label': ('PRESENTATION', 'order_flow_engine.py:OrderFlowEngine.compute'),
    'regime_primary': ('CONTROL', None),
    'regime_secondary': ('CONTROL', None),
    'regime_confidence': ('CONTROL', None),
    'regime_score': ('CONTROL', None),
    'regime_summary': ('PRESENTATION', None),
    'regime_support': ('CONTROL', None),
    'regime_contradiction': ('CONTROL', None),
    'fusion_available': ('DECISION', None),
    'fusion_dominant': ('DECISION', None),
    'fusion_dominant_prob': ('DECISION', None),
    'fusion_confidence': ('DECISION', None),
    'fusion_confidence_score': ('DECISION', None),
    'fusion_summary': ('PRESENTATION', None),
    'fusion_breakout': ('DECISION', None),
    'fusion_pinning': ('DECISION', None),
    'fusion_continuation': ('DECISION', None),
    'fusion_reversal': ('DECISION', None),
    'fusion_vol_expansion': ('DECISION', None),
    'fusion_mean_reversion': ('DEBUG', None),
    'fusion_model_agreement': ('DECISION', None),
    'fusion_agreement_label': ('PRESENTATION', None),
    'fusion_n_models_active': ('DECISION', None),
    'fusion_prob_up': ('DECISION', None),
    'fusion_prob_down': ('DECISION', None),
    'fusion_prob_flat': ('DECISION', None),
    'fusion_dominant_direction': ('DECISION', None),
    'fusion_evidence': ('DECISION', None),
    'fusion_contradictions': ('DECISION', None),
    'fusion_mc_contribution': ('DECISION', None),
    'option_chain_selection_proof': ('MARKET', None),
    'mc_available': ('DECISION', None),
    'mc_containment': ('DECISION', None),
    'mc_expansion': ('DECISION', None),
    'mc_efe': ('DECISION', None),
    'mc_eae': ('DECISION', None),
    'mc_upper_50': ('DECISION', None),
    'mc_lower_50': ('DECISION', None),
    'mc_paths': ('DECISION', None),
    'mc_horizon': ('DECISION', None),
    'mc_vol_source': ('DECISION', None),
    'mc_sigma_value': ('DECISION', None),
    'mc_conditioning': ('DECISION', None),
    'mc_horizon_minutes': ('DECISION', None),
    'stack_directional_authorized': ('DECISION', None),
    'stack_directional_authorization_reason': ('CONTROL', None),
    'mc_em_anchor': ('DECISION', None),
    'mc_iv_source': ('DECISION', None),
    'mc_efe_5m': ('DECISION', None),
    'mc_eae_5m': ('DECISION', None),
    'mc_efe_15m': ('DECISION', None),
    'mc_eae_15m': ('DECISION', None),
    'xgb_available': ('MARKET', None),
    'xgb_dominant': ('MARKET', None),
    'xgb_confidence': ('DECISION', None),
    'xgb_approved': ('MARKET', None),
    'lstm_available': ('MARKET', None),
    'lstm_dominant': ('MARKET', None),
    'lstm_confidence': ('DECISION', None),
    'lstm_approved': ('MARKET', None),
    'transformer_available': ('MARKET', None),
    'transformer_dominant': ('MARKET', None),
    'transformer_confidence': ('DECISION', None),
    'transformer_approved': ('MARKET', None),
    'ml_layer_probs': ('DECISION', None),
    'stack_decision_path': ('MARKET', None),
    'nearest_above_name': ('MARKET', None),
    'nearest_above_val': ('MARKET', None),
    'nearest_above_dist': ('MARKET', None),
    'nearest_below_name': ('MARKET', None),
    'nearest_below_val': ('MARKET', None),
    'nearest_below_dist': ('MARKET', None),
    'vwap_side': ('MARKET', 'math_snapshot_derive.py:derive_vwap_side'),
    'charm_net': ('MARKET', None),
    'charm_direction': ('DECISION', None),
    'charm_direction_display': ('PRESENTATION', None),
    'charm_drift_toward': ('MARKET', None),
    'charm_magnitude': ('MARKET', None),
    'charm_top_drivers': ('MARKET', None),
    'live_on': ('MARKET', None),
    'state_error': ('CONTROL', None),
    'state_error_detail': ('CONTROL', None),
    'signals_engine_failed': ('CONTROL', None),
    'stack_integrity_events': ('MARKET', None),
    'liquidity_behavior': ('MARKET', None),
    'news_context': ('MARKET', None),
}

ENGINE_INPUTS: dict[tuple[str, str], dict[str, str | None]] = {
    ('call_engine.py', 'compute_call'): {
        'inp': None,
        'rules': None,
        'pred': None,
        'regime': None,
        'fusion': None,
        'vol_regime': None,
        'canonical': None,
        'mvp_features': None,
        'mh_policy': None,
    },
    ('call_engine.py', 'compute_position_size'): {
        'signal': None,
        'conviction': None,
        'trade_type': None,
        'confluence_count': None,
        'confluence_total': None,
        'regime_label': None,
        'regime_confidence': None,
        'atr': None,
        'iv_level': None,
        'vix': None,
        'stop_distance': None,
        'mc_eae': None,
        'mc_efe': None,
        'mc_containment': None,
        'mc_expansion': None,
        'model_agreement': None,
        'fusion_confidence': None,
        'n_models_active': None,
        'dist_to_nearest_opposing_wall': None,
        'has_void_ahead': None,
        'reward_risk': None,
        'validation_passed': None,
        'mins_to_close': None,
        'vol_regime_risk_multiplier': None,
    },
    ('multi_horizon_decision.py', 'compute_multi_horizon_synthesis'): {
        'inp': None,
        'pred': None,
        'canonical': None,
        'mh_ml_bundle': None,
        'pool_weights': None,
    },
    ('prediction_engine.py', 'compute_prediction'): {
        'inp': None,
        'db': None,
        'regime': None,
        'fusion': None,
        'rules': None,
        'mc_out': None,
        'canonical': None,
        'ml_bundle': None,
        'multi_horizon_ml_bundle': None,
        'inference_snapshot_v1': None,
    },
    ('decision_gate.py', 'evaluate_decision_path_admission'): {
        'component': None,
        'path': None,
    },
}

#: Keys the serializer adds to the card payload OUTSIDE MarketState (B2 payload fields).
PAYLOAD_EXTRAS: dict[str, tuple[str, str | None]] = {
    'em_straddle_upper': ('MARKET', 'server.py:_fetch_state'),
    'em_straddle_lower': ('MARKET', 'server.py:_fetch_state'),
    'kl_em_upper': ('MARKET', 'server.py:_terrain_kl_overlay'),
    'kl_em_lower': ('MARKET', 'server.py:_terrain_kl_overlay'),
    'analytics_stale': ('CONTROL', 'server.py:_attach_analytics_freshness_contract'),
    'analytics_pending_shell': ('CONTROL', 'server.py:_attach_analytics_freshness_contract'),
    'analytics_refresh_in_progress': ('CONTROL', 'server.py:_attach_analytics_freshness_contract'),
}

#: Roots with no producer yet — NOT_PROVEN, by name. The suite asserts this list is EXACT:
#: a root cannot go OPEN silently, and a root that closes must leave this list.
OPEN_ROOTS: tuple[str, ...] = (
    '/api/expiries',
    '/api/terrain/scorecard',
    'ask',
    'avg_15c_pts',
    'avg_5c_pts',
    'avg_60c_pts',
    'bias_resolved',
    'bias_signal',
    'bid',
    'call_conviction',
    'call_engine.py:compute_call/canonical',
    'call_engine.py:compute_call/fusion',
    'call_engine.py:compute_call/inp',
    'call_engine.py:compute_call/mh_policy',
    'call_engine.py:compute_call/mvp_features',
    'call_engine.py:compute_call/pred',
    'call_engine.py:compute_call/regime',
    'call_engine.py:compute_call/rules',
    'call_engine.py:compute_call/vol_regime',
    'call_engine.py:compute_position_size/atr',
    'call_engine.py:compute_position_size/confluence_count',
    'call_engine.py:compute_position_size/confluence_total',
    'call_engine.py:compute_position_size/conviction',
    'call_engine.py:compute_position_size/dist_to_nearest_opposing_wall',
    'call_engine.py:compute_position_size/fusion_confidence',
    'call_engine.py:compute_position_size/has_void_ahead',
    'call_engine.py:compute_position_size/iv_level',
    'call_engine.py:compute_position_size/mc_containment',
    'call_engine.py:compute_position_size/mc_eae',
    'call_engine.py:compute_position_size/mc_efe',
    'call_engine.py:compute_position_size/mc_expansion',
    'call_engine.py:compute_position_size/mins_to_close',
    'call_engine.py:compute_position_size/model_agreement',
    'call_engine.py:compute_position_size/n_models_active',
    'call_engine.py:compute_position_size/regime_confidence',
    'call_engine.py:compute_position_size/regime_label',
    'call_engine.py:compute_position_size/reward_risk',
    'call_engine.py:compute_position_size/signal',
    'call_engine.py:compute_position_size/stop_distance',
    'call_engine.py:compute_position_size/trade_type',
    'call_engine.py:compute_position_size/validation_passed',
    'call_engine.py:compute_position_size/vix',
    'call_engine.py:compute_position_size/vol_regime_risk_multiplier',
    'call_forecast_state',
    'call_missing_conditions',
    'call_option_expiry',
    'call_option_right',
    'call_readiness_component_scores',
    'call_readiness_reasons',
    'call_readiness_score',
    'call_reasoning',
    'call_signal',
    'call_state',
    'call_wait_blocker',
    'canonical_provenance',
    'charm_direction',
    'charm_drift_toward',
    'charm_magnitude',
    'charm_net',
    'charm_top_drivers',
    'confidence',
    'confluence_detail',
    'confluence_total',
    'contradiction_state',
    'decision_gate.py:evaluate_decision_path_admission/component',
    'decision_gate.py:evaluate_decision_path_admission/path',
    'decision_provenance',
    'dex_magnitude',
    'dominant_dir',
    'dominant_prob',
    'down_prob_15c',
    'down_prob_1c',
    'down_prob_5c',
    'down_prob_60c',
    'dte_warn',
    'empirical_confidence',
    'entry',
    'entry_state',
    'entry_zone_hi',
    'entry_zone_lo',
    'eval_accuracy_oos',
    'eval_log_loss_oos',
    'eval_pnl_realized_contract_oos',
    'eval_realized_contract_metrics_oos',
    'event_risk_detail',
    'event_risk_level',
    'execution_mode',
    'final_bias',
    'final_confidence',
    'final_quality',
    'final_tradeable',
    'flat_prob_15c',
    'flat_prob_1c',
    'flat_prob_5c',
    'flat_prob_60c',
    'forward_prob_down',
    'forward_prob_flat',
    'forward_prob_up',
    'forward_provenance',
    'fusion_available',
    'fusion_breakout',
    'fusion_confidence',
    'fusion_confidence_score',
    'fusion_continuation',
    'fusion_contradictions',
    'fusion_dominant',
    'fusion_dominant_direction',
    'fusion_dominant_prob',
    'fusion_evidence',
    'fusion_mc_contribution',
    'fusion_model_agreement',
    'fusion_n_models_active',
    'fusion_pinning',
    'fusion_policy_snapshot_cols',
    'fusion_prob_down',
    'fusion_prob_flat',
    'fusion_prob_up',
    'fusion_reversal',
    'fusion_vol_expansion',
    'guest_anchor_active',
    'guest_anchor_affiliation',
    'guest_anchor_rationale',
    'guest_anchor_weights_ticker',
    'historical_5c_dominant_dir',
    'historical_5c_dominant_prob',
    'horizon_directional_authorization_reason',
    'horizon_directional_authorized',
    'horizon_fusion_available',
    'horizon_prob_bars',
    'invalidation',
    'is_no_trade',
    'iv_direction',
    'last_sweep_held',
    'last_sweep_level',
    'last_sweep_type',
    'liquidity_behavior',
    'live_on',
    'lstm_approved',
    'lstm_available',
    'lstm_confidence',
    'lstm_dominant',
    'mc_available',
    'mc_conditioning',
    'mc_containment',
    'mc_eae',
    'mc_eae_15m',
    'mc_eae_5m',
    'mc_efe',
    'mc_efe_15m',
    'mc_efe_5m',
    'mc_em_anchor',
    'mc_expansion',
    'mc_horizon',
    'mc_horizon_minutes',
    'mc_iv_source',
    'mc_lower_50',
    'mc_paths',
    'mc_sigma_value',
    'mc_upper_50',
    'mc_vol_source',
    'mh_prob_source_by_horizon',
    'mh_promoted_directional',
    'mhap_legend',
    'mhap_rows',
    'ml_layer_probs',
    'model_serving_provenance_v1',
    'movement_head_probs',
    'multi_horizon_decision.py:compute_multi_horizon_synthesis/canonical',
    'multi_horizon_decision.py:compute_multi_horizon_synthesis/inp',
    'multi_horizon_decision.py:compute_multi_horizon_synthesis/mh_ml_bundle',
    'multi_horizon_decision.py:compute_multi_horizon_synthesis/pool_weights',
    'multi_horizon_decision.py:compute_multi_horizon_synthesis/pred',
    'n_sweeps_today',
    'nd_resolved',
    'nearest_above_dist',
    'nearest_above_name',
    'nearest_above_val',
    'nearest_below_dist',
    'nearest_below_name',
    'nearest_below_val',
    'news_context',
    'option_chain_selection_proof',
    'pin_strength',
    'pred_dominant_by_horizon',
    'pred_model_source',
    'pred_override_source',
    'prediction_engine.py:compute_prediction/canonical',
    'prediction_engine.py:compute_prediction/db',
    'prediction_engine.py:compute_prediction/fusion',
    'prediction_engine.py:compute_prediction/inference_snapshot_v1',
    'prediction_engine.py:compute_prediction/inp',
    'prediction_engine.py:compute_prediction/mc_out',
    'prediction_engine.py:compute_prediction/ml_bundle',
    'prediction_engine.py:compute_prediction/multi_horizon_ml_bundle',
    'prediction_engine.py:compute_prediction/regime',
    'prediction_engine.py:compute_prediction/rules',
    'primary_horizon',
    'probability_valid',
    'put_forecast_state',
    'put_missing_conditions',
    'put_readiness_component_scores',
    'put_readiness_reasons',
    'put_readiness_score',
    'put_state',
    'r_units',
    'rec_side',
    'rec_strike',
    'regime_confidence',
    'regime_contradiction',
    'regime_primary',
    'regime_score',
    'regime_secondary',
    'regime_support',
    'replay_max_hold_bars',
    'reversal_risk',
    'reversal_severity',
    'reversal_shortfall',
    'reward_risk',
    'reward_risk2',
    'risk_valid',
    'rules_alerts',
    'rules_conviction',
    'rules_detail',
    'rules_pred_agree',
    'rules_signal',
    'samples_used',
    'selected_exp',
    'session_high',
    'session_low',
    'signals_engine_failed',
    'size_cue',
    'spot',
    'stack_decision_path',
    'stack_directional_authorization_reason',
    'stack_directional_authorized',
    'stack_integrity_events',
    'state_error',
    'state_error_detail',
    'stop',
    'structure_valid',
    'target',
    'target2',
    'ticker',
    'time_qualifier',
    'time_warning',
    'timeframe_reads',
    'trade_mode',
    'trade_type',
    'transformer_approved',
    'transformer_available',
    'transformer_confidence',
    'transformer_dominant',
    'up_prob_15c',
    'up_prob_1c',
    'up_prob_5c',
    'up_prob_60c',
    'validation_passed',
    'vix',
    'vix_implication',
    'vix_regime',
    'vol_regime',
    'vol_regime_conviction_mult',
    'vol_regime_risk_mult',
    'wait_reason',
    'xgb_approved',
    'xgb_available',
    'xgb_confidence',
    'xgb_dominant',
)
