"""
Section 10 Schwab-leaf derivation audit inventory (ML training + predict).

One row per ``def`` (module, class method, nested helper).
Disposition: REPLACED | KEEP_DERIVED | PASS_THROUGH | NONE
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DerivationRecord:
    file: str
    line: str
    derivation: str
    schwab_leaf: str
    disposition: str
    justification: str


SECTION10_DERIVATION_INVENTORY: tuple[DerivationRecord, ...] = (

    DerivationRecord("lstm_data.py", "35", "_positive_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_data.py", "137", "_encode_zone_feature", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "144", "_encode_vwap_side_feature", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "158", "compute_confluence_features", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "269", "compute_confluence_features._sign", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_data.py", "295", "_connect", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "304", "_is_rth", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_data.py", "310", "_snapshot_table_for_timeframe", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "324", "extract_rth_snapshots", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "424", "_safe_float", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_data.py", "434", "canonical_reference_spot_from_sequence_window_first_bar", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "453", "_signed_log", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_data.py", "463", "encode_snapshot_5m", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "516", "encode_snapshot_1m", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "585", "LSTMDataset.summary", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_data.py", "626", "build_lstm_dataset", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "28", "lstm_model_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "37", "lstm_meta_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "56", "_lstm_xgb_probs_fp", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("lstm_model.py", "63", "_persist_lstm_resume_checkpoint", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "112", "build_model", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "118", "DualStreamLSTM.build_model.__init__", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "150", "DualStreamLSTM.build_model._init_weights", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "165", "DualStreamLSTM.build_model.forward", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("lstm_model.py", "183", "compute_feature_masks", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "204", "apply_masks", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "212", "compute_normalization", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "231", "apply_normalization", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "239", "align_lstm_norm_stats", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("lstm_model.py", "257", "align_lstm_norm_stats._one", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "306", "TrainResult.summary", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lstm_model.py", "313", "train_lstm", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("lstm_model.py", "601", "load_lstm", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "24", "rth_where_clause", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_data_common.py", "31", "training_label_where_clause", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_data_common.py", "64", "outcome_where_clause", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "75", "weekday_where_clause", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "79", "compute_exponential_weights", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "101", "_db_default_path", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_data_common.py", "138", "fetch_m5_additive_dict", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "174", "snapshot_with_m5_additive", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_data_common.py", "184", "attach_5m_additive_context", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "79", "normalize_ml_horizon_slug", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_horizon.py", "101", "is_primary_decision_horizon", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "117", "is_secondary_support_horizon", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "133", "outcome_column", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "145", "directional_label_column", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "157", "move_label_column", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "169", "default_training_label_column", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_horizon.py", "179", "live_inference_horizon_slug", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_horizon.py", "189", "live_stack_probs_bundle_key", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_horizon.py", "207", "target_definition", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_horizon.py", "223", "promotion_definition_substring", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "74", "_reg_key", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "78", "_model_registry_key", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "90", "_cascade_challenger_inference_scope", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "104", "get_ml_infer_horizon_slug", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_predict.py", "108", "set_ml_infer_horizon_slug", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_predict.py", "112", "reset_ml_infer_horizon_slug", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_predict.py", "116", "stack_probs_bundle_key", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "126", "_snap_dict", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "137", "_require_as_of_ts_utc_for_sequence_db", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "154", "_probs_dict_to_arr", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "164", "_transformer_normalize_and_select", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "203", "_model_dir_for_ticker", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "315", "build_xgb_pre_engineering_snapshot_for_tick", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "343", "_load_xgb", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "391", "_predict_xgb", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "467", "_normalize_binary_head_probs", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "484", "_predict_xgb_movement_heads", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "614", "_load_lstm", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "653", "_predict_lstm", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "814", "_load_transformer", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "870", "_predict_transformer", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "1023", "_load_meta", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1046", "_stack_probs", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "1049", "_stack_probs._to_vec", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1055", "_predict_meta", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "1067", "_weighted_average", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1088", "_apply_5c_xgb_plus_transformer_isotonic_calibration", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1142", "run_base_models_once", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1214", "run_base_models_once._to_fusion_out", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1238", "run_base_models_once._to_ui_output", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1260", "run_base_models_once._parallel_model_output_record", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1319", "run_cascade_models_once", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1353", "run_cascade_models_once._fusion_out", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1379", "run_cascade_models_once._parallel_model_output_record", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1477", "get_model_outputs_for_fusion", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1500", "get_model_outputs", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1531", "predict_direction", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "1560", "predict_all_horizons", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_predict.py", "1579", "is_available", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1590", "get_model_version", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_predict.py", "1604", "get_component_status", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_predict.py", "1615", "reset_caches", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("ml_predict.py", "1626", "_fmt", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_scheduler.py", "62", "scheduler_arch_state_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "69", "scheduler_active_root", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "76", "_infer_slug_from_target_column", "—", "NONE", "Horizon slug / scheduler bookkeeping."),
    DerivationRecord("ml_scheduler.py", "83", "_now_et", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "87", "_scheduler_auto_promote_to_active", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_scheduler.py", "93", "_strict_off_for_candidate_inference", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("ml_scheduler.py", "107", "_append_training_report", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_scheduler.py", "115", "_is_market_day", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "126", "_wait_until_1615", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_scheduler.py", "135", "_training_ticker_union", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_scheduler.py", "155", "_get_tickers_with_rth_data", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "180", "_diagnostic_db_tickers_not_enrolled", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "198", "_load_rth_rows_for_ticker", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "225", "_empty_realized_metrics", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "255", "_evaluate_parallel_on_full_rth", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "388", "_evaluate_cascade_on_full_rth", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "505", "train_parallel_candidate", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_scheduler.py", "785", "_train_parallel", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_scheduler.py", "816", "train_cascade_candidate", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_scheduler.py", "904", "train_cascade_candidate._ts_ok", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_scheduler.py", "1209", "_train_cascade", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_scheduler.py", "1240", "_artifact_paths_relative", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "1254", "run_once", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "2174", "_next_scheduled_run_et", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "2188", "start_background_scheduler", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_scheduler.py", "2202", "start_background_scheduler._loop", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "54", "xgb_meta_contract_ok", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_train.py", "62", "apply_xgb_imputation_matrix", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "80", "model_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "99", "meta_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "188", "load_data", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "279", "engineer_features", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "413", "engineer_single_snapshot", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "428", "engineer_single_snapshot._f", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "432", "engineer_single_snapshot._pct", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_train.py", "540", "get_model", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_train.py", "569", "compute_sample_weights", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("ml_train.py", "585", "encode_target", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "589", "_xgb_append_only_ok", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("ml_train.py", "611", "train_ticker", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("ml_train.py", "805", "main", "—", "NONE", "CLI entrypoint; no market-field derivation."),
    DerivationRecord("normalized_training_sync.py", "40", "_table_exists", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("normalized_training_sync.py", "48", "_aggregate_select_exprs", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("normalized_training_sync.py", "79", "compute_snapshots_training_fingerprint", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("normalized_training_sync.py", "106", "_get_stored_fp", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("normalized_training_sync.py", "116", "_set_stored_fp", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("normalized_training_sync.py", "129", "persist_training_fingerprint_after_materialize", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("normalized_training_sync.py", "155", "verify_normalized_freshness", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("normalized_training_sync.py", "177", "ensure_normalized_training_table", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("normalized_training_sync.py", "261", "schedule_debounced_normalized_refresh", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("normalized_training_sync.py", "278", "schedule_debounced_normalized_refresh._fire", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("smoke_predict_active.py", "33", "_tickers_from_active", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("smoke_predict_active.py", "55", "main", "active models", "KEEP_DERIVED", "Smoke test predict path on active artifacts."),
    DerivationRecord("train_all.py", "27", "run_xgb", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "73", "run_lstm", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "108", "run_transformer", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "143", "run_meta", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "258", "_HistoricalDB.__init__", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_all.py", "263", "_HistoricalDB.get_recent_snapshots", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "300", "PreloadedHistoricalDB.__init__", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "306", "PreloadedHistoricalDB.get_recent_snapshots", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "335", "preload_historical_db_for_eval", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_all.py", "363", "main", "—", "NONE", "CLI orchestration for batch training."),
    DerivationRecord("train_compare.py", "33", "_safe_stdout_ctx", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_compare.py", "37", "_Writable._safe_stdout_ctx.write", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_compare.py", "43", "_Writable._safe_stdout_ctx.flush", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_compare.py", "49", "_compute_baseline", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_compare.py", "60", "_rel_artifacts", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("train_compare.py", "72", "validate_eval_slice_parity", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("train_compare.py", "91", "main", "—", "NONE", "CLI entrypoint; no market-field derivation."),
    DerivationRecord("training_cache.py", "43", "_app_models_dir", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "47", "file_sha256_hex", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "55", "compute_training_code_fingerprint", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "73", "xgb_meta_content_sha256", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "79", "db_training_fingerprint", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("training_cache.py", "119", "compute_scheduler_cache_key", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "167", "compute_feature_cache_key", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "204", "feature_cache_dir", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "210", "db_distinct_rth_et_dates_for_ticker", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "232", "min_ts_utc_for_last_n_rth_sessions", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "266", "compare_tabular_data_fingerprint_from_df", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "295", "_normalize_data_fp", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "300", "_normalize_data_fp._num", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "315", "_canonical_lineage_identity_ok", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "329", "_write_feature_identity", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "349", "_feature_identity_matches", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "366", "save_lstm_feature_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "406", "load_lstm_feature_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "454", "save_transformer_parallel_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "477", "load_transformer_parallel_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "497", "cascade_tensor_bind_slug", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "506", "xgb_lstm_tensor_sha256", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "511", "cascade_tensor_cache_dir_name", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "516", "_cascade_tensor_subdir_for_save", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "524", "_iter_cascade_tensor_subdirs", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "535", "_cascade_identity_matches", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "573", "save_cascade_transformer_tensor_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "610", "load_cascade_transformer_tensor_cache", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "647", "compute_artifact_sha256_map", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "656", "validate_manifest_artifact_hashes", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "684", "trained_at_age_days", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("training_cache.py", "698", "full_skip_eligible", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "769", "archive_candidate_directory_before_train", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("training_cache.py", "797", "prune_model_archives", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "838", "cleanup_feature_cache_directories", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "869", "candidate_manifest_path", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "873", "load_run_manifest", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "884", "save_run_manifest", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "891", "compare_aggregate_manifest_path", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "897", "save_compare_aggregate_manifest", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "904", "parallel_artifact_basenames", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "918", "cascade_artifact_basenames", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "922", "artifacts_present", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_cache.py", "933", "manifest_matches_current", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "968", "build_manifest", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "1004", "build_manifest._ts_label", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache.py", "1047", "cache_exists", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache.py", "1061", "read_cache_meta", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_cache_policy.py", "34", "training_repo_root", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_cache_policy.py", "38", "env_disable_torch_resume", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_provenance.py", "84", "TrainingProvenance.to_dict", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_provenance.py", "88", "TrainingProvenance.from_dict", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_provenance.py", "89", "TrainingProvenance.from_dict._get", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("training_provenance.py", "115", "cache_key", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "133", "is_provenance_compliant", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "152", "validate_for_promotion", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("training_provenance.py", "209", "load_provenance", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "223", "provenance_rows", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "228", "build_xgb_provenance", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "263", "build_lstm_provenance", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("training_provenance.py", "302", "build_transformer_provenance", "—", "NONE", "Training cache/provenance metadata; no market derivation."),
    DerivationRecord("transformer_model.py", "44", "_horizon_label_from_meta", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_model.py", "96", "_prepare_sequence", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_model.py", "164", "predict", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("transformer_model.py", "288", "_fallback", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("transformer_train.py", "41", "transformer_model_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "50", "transformer_meta_path", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "72", "TransformerTrainResult.summary", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("transformer_train.py", "80", "build_transformer", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "85", "PositionalEncoding.build_transformer.__init__", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("transformer_train.py", "95", "PositionalEncoding.build_transformer.forward", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("transformer_train.py", "99", "TransformerClassifier.build_transformer.__init__", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "116", "TransformerClassifier.build_transformer._init_weights", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("transformer_train.py", "123", "TransformerClassifier.build_transformer.forward", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("transformer_train.py", "137", "prepare_transformer_data", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "220", "_cascade_tensor_fp", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "230", "_persist_transformer_resume_checkpoint", "snapshots.* / feature columns", "KEEP_DERIVED", "ML data prep from upstream canonical inputs."),
    DerivationRecord("transformer_train.py", "274", "train_transformer", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
    DerivationRecord("xgboost_model.py", "55", "predict", "model features / InferenceSnapshotV1", "KEEP_DERIVED", "Inference on canonical features; no Schwab wire ingest."),
    DerivationRecord("xgboost_model.py", "165", "_fallback", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("xgboost_model.py", "179", "train", "snapshots.* / training features", "KEEP_DERIVED", "Training path on persisted snapshot/feature rows."),
)

SECTION10_FILES = frozenset({
    "lstm_data.py",
    "lstm_model.py",
    "ml_data_common.py",
    "ml_horizon.py",
    "ml_predict.py",
    "ml_scheduler.py",
    "ml_train.py",
    "normalized_training_sync.py",
    "smoke_predict_active.py",
    "train_all.py",
    "train_compare.py",
    "training_cache.py",
    "training_cache_policy.py",
    "training_provenance.py",
    "transformer_model.py",
    "transformer_train.py",
    "xgboost_model.py",
})

