"""
Section 4 Schwab-leaf derivation audit inventory (KEY LEVELS re-walk).

One row per module-level function. Disposition: REPLACED | KEEP_DERIVED | PASS_THROUGH | NONE
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DerivationRecord:
    file: str
    line: str
    derivation: str
    schwab_leaf: str
    disposition: str
    justification: str


SECTION4_DERIVATION_INVENTORY: tuple[DerivationRecord, ...] = (
    DerivationRecord("math_exposure.py", "52", "_of_sign", "—", "NONE", "Sign helper on order-flow scalar."),
    DerivationRecord("math_exposure.py", "63", "_of_direction", "—", "NONE", "Direction label from scalar."),
    DerivationRecord("math_exposure.py", "78", "compute_order_flow_verdict", "cum_delta,book_imb,opt_flow (upstream Schwab)", "KEEP_DERIVED", "Composite verdict; inputs must be Schwab-first from OF engine."),
    DerivationRecord("math_exposure.py", "140", "_book_direction", "—", "NONE", "Book imbalance label bands."),
    DerivationRecord("math_exposure.py", "155", "order_flow_score_label", "—", "NONE", "Display label for OF score."),
    DerivationRecord("math_exposure.py", "161", "order_flow_book_label", "—", "NONE", "Display label for book imbalance."),
    DerivationRecord("math_exposure.py", "176", "order_flow_opt_label", "—", "NONE", "Display label for option flow."),
    DerivationRecord("math_exposure.py", "191", "order_flow_field_arrow", "—", "NONE", "UI arrow from signed field."),
    DerivationRecord("math_exposure.py", "202", "fmt_money", "—", "NONE", "Money formatter."),
    DerivationRecord("math_exposure.py", "213", "fmt_money_gex", "—", "NONE", "GEX money formatter."),
    DerivationRecord("math_exposure_core.py", "20", "_f", "—", "NONE", "Safe float parse."),
    DerivationRecord("math_exposure_core.py", "29", "bucket_metric", "chains.* bucket keys", "PASS_THROUGH", "Fail-closed; no .get(k,0)."),
    DerivationRecord("math_exposure_core.py", "36", "bucket_metric_abs", "chains.* bucket keys", "PASS_THROUGH", "Abs of bucket_metric."),
    DerivationRecord("math_exposure_core.py", "66", "_strike_bucket", "chains.*", "PASS_THROUGH", "Strike dict lookup."),
    DerivationRecord("math_exposure_core.py", "102", "compute_exposures_by_strike", "chains.*.delta,gamma,OI,multiplier,bidSize,askSize", "PASS_THROUGH", "Core Schwab chain aggregation; skip -999 greeks."),
    DerivationRecord("math_exposure_core.py", "255", "_nearest_strike", "chains.*.strikePrice", "PASS_THROUGH", "ATM strike selection."),
    DerivationRecord("math_exposure_core.py", "266", "_window_strikes", "chains.*.strikePrice", "PASS_THROUGH", "Strike window filter."),
    DerivationRecord("math_exposure_core.py", "282", "exposures_have_dollar_gex", "derived buckets", "KEEP_DERIVED", "Detects dollarized GEX availability."),
    DerivationRecord("math_exposure_core.py", "292", "key_level_strikes_with_oi", "chains.*.openInterest", "PASS_THROUGH", "Strikes with OI leaf."),
    DerivationRecord("math_exposure_core.py", "305", "key_level_strikes_with_gamma", "chains.*.gamma", "PASS_THROUGH", "Strikes with usable gamma."),
    DerivationRecord("math_exposure_core.py", "321", "total_gex_dollars_at_strike", "derived net_gex_1pct", "KEEP_DERIVED", "Sum |call|+|put| GEX$."),
    DerivationRecord("math_exposure_core.py", "333", "net_gex_dollars_at_strike", "derived net_gex_1pct", "KEEP_DERIVED", "Net GEX$ at strike."),
    DerivationRecord("math_exposure_core.py", "337", "total_gamma_raw_at_strike", "chains.*.gamma", "KEEP_DERIVED", "Raw gamma magnitude fallback."),
    DerivationRecord("math_exposure_core.py", "348", "net_gamma_raw_at_strike", "chains.*.gamma", "KEEP_DERIVED", "Raw net gamma."),
    DerivationRecord("math_exposure_core.py", "352", "_pick_strike_max_metric", "exposure buckets", "KEEP_DERIVED", "Max-metric strike picker."),
    DerivationRecord("math_exposure_core.py", "370", "pick_gamma_pin_strike", "chains.* via GEX$", "KEEP_DERIVED", "Institutional pin; no raw fallback when dollarized."),
    DerivationRecord("math_exposure_core.py", "393", "pick_hvl_strike", "chains.* gamma/GEX$", "KEEP_DERIVED", "High-vol level strike."),
    DerivationRecord("math_exposure_core.py", "405", "pick_gamma_wall_strikes", "chains.* gamma/GEX$", "KEEP_DERIVED", "Call/put gamma walls."),
    DerivationRecord("math_exposure_core.py", "428", "pick_delta_wall_strikes", "chains.* delta/DEX$", "KEEP_DERIVED", "Call/put delta walls."),
    DerivationRecord("math_exposure_core.py", "450", "aggregate_net_gex", "derived buckets", "KEEP_DERIVED", "Sum net_gex_1pct over strikes."),
    DerivationRecord("math_exposure_core.py", "474", "aggregate_net_dex", "derived buckets", "KEEP_DERIVED", "Sum net_dex over strikes."),
    DerivationRecord("math_exposure_core.py", "496", "gex_magnitude_label", "derived net_gex", "KEEP_DERIVED", "Label from GEX magnitude."),
    DerivationRecord("math_exposure_core.py", "509", "gex_regime_label", "derived net_gex", "KEEP_DERIVED", "Regime label from sign of GEX."),
    DerivationRecord("math_exposure_core.py", "517", "greeks_validity", "chains.* greek counts", "KEEP_DERIVED", "Validity gate on greek coverage."),
    DerivationRecord("math_exposure_core.py", "531", "sanitize_dealer_metrics", "DEX/GEX aggregates", "KEEP_DERIVED", "Sanitize when greeks invalid."),
    DerivationRecord("math_exposure_core.py", "541", "window_summary", "exposure buckets", "KEEP_DERIVED", "Window-level DEX/GEX/OI summary."),
    DerivationRecord("math_exposure_core.py", "567", "strike_agg", "single strike bucket", "PASS_THROUGH", "Single-strike bucket read."),
    DerivationRecord("math_exposure_core.py", "573", "compute_net_charm", "chains.*.charm,OI", "KEEP_DERIVED", "Net charm from chain; Schwab charm leaf when present."),
    DerivationRecord("math_exposure_core.py", "745", "greek_bias", "net_delta,charm_direction", "KEEP_DERIVED", "Bias string from greeks."),
    DerivationRecord("math_exposure_core.py", "778", "compute_beta", "pricehistory.candles.close", "KEEP_DERIVED", "Beta from return series; inputs from Schwab candles."),
    DerivationRecord("math_exposure_core.py", "820", "compute_beta_residual", "quote chg_pct", "KEEP_DERIVED", "Residual vs SPY; quote-derived inputs."),
    DerivationRecord("math_exposure_core.py", "830", "returns_from_candles", "pricehistory.candles.datetime,close", "PASS_THROUGH", "Daily returns; datetime required (cross-section fix)."),
    DerivationRecord("math_levels.py", "116", "_pick_gamma_pin", "exposures", "KEEP_DERIVED", "Delegates pick_gamma_pin_strike."),
    DerivationRecord("math_levels.py", "120", "_pick_oi_center", "chains.*.openInterest", "KEEP_DERIVED", "OI-weighted center."),
    DerivationRecord("math_levels.py", "138", "_pick_inflection_closest_zero", "exposure buckets", "KEEP_DERIVED", "Zero-cross inflection picker."),
    DerivationRecord("math_levels.py", "157", "_pin_strength", "net_gamma buckets", "KEEP_DERIVED", "Pin strength vs neighbors."),
    DerivationRecord("math_levels.py", "194", "_bias_from_net", "net_gamma,net_delta", "KEEP_DERIVED", "Bias signal taxonomy."),
    DerivationRecord("math_levels.py", "215", "build_summary_rows", "exposures,spot", "KEEP_DERIVED", "KEY LEVELS summary table rows."),
    DerivationRecord("math_levels.py", "289", "_pick_wall_abs", "exposure buckets", "KEEP_DERIVED", "Legacy abs wall picker."),
    DerivationRecord("math_levels.py", "305", "_pick_wall_pos", "exposure buckets", "KEEP_DERIVED", "Positive-metric wall picker."),
    DerivationRecord("math_levels.py", "324", "_dominant", "wall strengths", "KEEP_DERIVED", "Dominant side selection."),
    DerivationRecord("math_levels.py", "339", "build_walls_rows", "exposures,spot", "KEEP_DERIVED", "Walls table for UI."),
    DerivationRecord("math_levels.py", "473", "build_totals_rows", "exposures", "KEEP_DERIVED", "Totals table aggregation."),
    DerivationRecord("math_levels.py", "575", "is_pin_zone", "zone string", "NONE", "Zone classifier constant check."),
    DerivationRecord("math_levels.py", "581", "parity_f_minus_spot_from_contracts", "chains.*.mark", "PASS_THROUGH", "Parity residual; mark-only mid per strike."),
    DerivationRecord("math_levels.py", "652", "compute_gamma_flip", "net_gamma/net_gex buckets", "KEEP_DERIVED", "Zero-cross interpolation."),
    DerivationRecord("math_levels.py", "729", "_total_gamma_at_strike", "GEX$/gamma buckets", "KEEP_DERIVED", "Total gamma measure at strike."),
    DerivationRecord("math_levels.py", "737", "compute_hvl", "exposures", "KEEP_DERIVED", "Delegates pick_hvl_strike."),
    DerivationRecord("math_levels.py", "750", "hvl_gamma_strength", "HVL strike bucket", "KEEP_DERIVED", "Strength at HVL."),
    DerivationRecord("math_levels.py", "762", "compute_max_pain", "chains.*.openInterest", "KEEP_DERIVED", "Max pain from OI; no Schwab max-pain leaf."),
    DerivationRecord("math_levels.py", "806", "max_pain_oi_strength", "max pain strike OI", "KEEP_DERIVED", "OI at max pain strike."),
    DerivationRecord("math_levels.py", "824", "compute_gamma_void_zones", "gamma/OI buckets", "REPLACED", "Void detection; gamma sum without or-zero synthesis."),
    DerivationRecord("math_levels.py", "976", "compute_level_density", "level list geometry", "KEEP_DERIVED", "Density metric for level bands."),
    DerivationRecord("math_volatility.py", "34", "_spot_atm_strike", "chains.*.strikePrice,spot", "PASS_THROUGH", "ATM strike from chain."),
    DerivationRecord("math_volatility.py", "39", "_extract_iv_for_strike", "chains.*.volatility", "PASS_THROUGH", "Mean call/put IV at strike; skip invalid."),
    DerivationRecord("math_volatility.py", "65", "charm_intraday_context", "compute_net_charm output", "KEEP_DERIVED", "Banner from charm_result dict."),
    DerivationRecord("math_volatility.py", "96", "session_bucket", "ET clock", "KEEP_DERIVED", "No Schwab session_label leaf."),
    DerivationRecord("math_volatility.py", "107", "vix_bucket", "quotes.$VIX", "PASS_THROUGH", "VIX level buckets from quote input."),
    DerivationRecord("math_volatility.py", "121", "compute_expected_move_straddle", "chains.*.mark,today_open", "KEEP_DERIVED", "EM from ATM marks; not single EM leaf."),
    DerivationRecord("math_volatility.py", "153", "compute_expected_move_iv", "chains.*.volatility,spot", "KEEP_DERIVED", "EM from IV + time; IV from Schwab volatility leaf."),
    DerivationRecord("math_volatility.py", "195", "resolve_kl_em_anchor", "EM straddle/IV dicts", "KEEP_DERIVED", "Anchor policy for KL+MC alignment."),
    DerivationRecord("math_volatility.py", "204", "iv_percent_from_em_pts", "EM pts,spot,hours", "KEEP_DERIVED", "Invert IV-EM formula."),
    DerivationRecord("math_volatility.py", "216", "resolve_mc_iv_for_kl_em_anchor", "kl anchor,atm_iv,straddle EM", "KEEP_DERIVED", "MC IV reconciled to KL anchor."),
    DerivationRecord("math_volatility.py", "239", "compute_em_progress", "spot,open,EM bounds", "KEEP_DERIVED", "Progress through EM range."),
    DerivationRecord("math_volatility.py", "286", "compute_iv_skew", "chains.*.volatility", "PASS_THROUGH", "Put IV minus call IV at ATM."),
    DerivationRecord("math_volatility.py", "346", "compute_realized_vol", "pricehistory.candles.close", "KEEP_DERIVED", "RV from closes; Schwab OHLC input."),
    DerivationRecord("math_volatility.py", "386", "compute_atr", "pricehistory.candles OHLC", "KEEP_DERIVED", "ATR from Schwab candles; skip incomplete bars."),
    DerivationRecord("math_volatility.py", "438", "compute_iv_rank", "chains.*.volatility history", "KEEP_DERIVED", "IV rank vs history series."),
    DerivationRecord("math_volatility.py", "467", "compute_iv_percentile", "chains.*.volatility history", "KEEP_DERIVED", "IV percentile vs history."),
    DerivationRecord("math_volatility.py", "494", "compute_volatility_envelope", "spot,ATR", "KEEP_DERIVED", "ATR bands around spot."),
    DerivationRecord("math_volatility.py", "571", "estimate_garch_params", "pricehistory closes", "KEEP_DERIVED", "GARCH param estimation from returns."),
    DerivationRecord("math_volatility.py", "637", "compute_garch_forecast", "pricehistory closes", "KEEP_DERIVED", "Forward sigma from GARCH."),
    DerivationRecord("math_volatility.py", "708", "blend_garch_sigma", "GARCH,IV,RV", "KEEP_DERIVED", "Blend GARCH+IV+RV per-bar sigma."),
    DerivationRecord("math_volatility.py", "765", "compute_iv_model_spread", "chains.*.volatility,theoreticalVolatility", "PASS_THROUGH", "Market vs model IV (OP-012)."),
    DerivationRecord("math_probabilities.py", "85", "_oe_wall_consensus_row", "walls rows", "PASS_THROUGH", "Wall row lookup."),
    DerivationRecord("math_probabilities.py", "95", "_wlevel", "walls row field", "PASS_THROUGH", "Wall level accessor."),
    DerivationRecord("math_probabilities.py", "102", "compute_wall_score_components", "walls,spot,strike", "KEEP_DERIVED", "Wall proximity scoring."),
    DerivationRecord("math_probabilities.py", "176", "score_option_expression", "chains.* bid,ask,gamma,delta,OI", "KEEP_DERIVED", "OE score; spread from bid-ask pts only."),
    DerivationRecord("math_probabilities.py", "269", "classify_direction", "pts_move,spot", "KEEP_DERIVED", "Direction from move threshold."),
    DerivationRecord("math_probabilities.py", "283", "dist_bucket", "distance", "KEEP_DERIVED", "Distance bucket label."),
    DerivationRecord("math_probabilities.py", "293", "bucket_lo", "bucket name", "NONE", "Bucket lower bound map."),
    DerivationRecord("math_probabilities.py", "300", "bucket_hi", "bucket name", "NONE", "Bucket upper bound map."),
    DerivationRecord("math_probabilities.py", "311", "compute_probs", "similar rows DB", "KEEP_DERIVED", "Historical outcome probabilities."),
    DerivationRecord("math_probabilities.py", "335", "dominant_direction", "up,down,flat probs", "KEEP_DERIVED", "Dominant class from probs."),
    DerivationRecord("math_probabilities.py", "343", "determine_confidence", "match tier,n", "KEEP_DERIVED", "Confidence label."),
    DerivationRecord("math_probabilities.py", "382", "_binomial_p_value", "—", "NONE", "Stats helper."),
    DerivationRecord("math_probabilities.py", "395", "compute_percentile_range", "similar rows", "KEEP_DERIVED", "Percentile band from history."),
    DerivationRecord("math_probabilities.py", "408", "classify_reversal_risk", "reversal prob", "KEEP_DERIVED", "Risk label."),
    DerivationRecord("math_probabilities.py", "429", "compute_dealer_pressure_index", "DEX,GEX,charm,vanna", "KEEP_DERIVED", "DPI composite."),
    DerivationRecord("math_probabilities.py", "479", "compute_hedging_flow_score", "DEX,GEX inputs", "KEEP_DERIVED", "Hedging flow score."),
    DerivationRecord("math_probabilities.py", "539", "compute_gamma_gradient", "GEX by strike", "KEEP_DERIVED", "dGEX/dPrice near spot."),
    DerivationRecord("math_probabilities.py", "589", "compute_breakout_score", "GEX,gradient,void", "KEEP_DERIVED", "Breakout composite."),
    DerivationRecord("math_probabilities.py", "640", "compute_pin_score", "GEX at pin", "KEEP_DERIVED", "Pin score from GEX."),
    DerivationRecord("math_probabilities.py", "688", "compute_vol_expansion_signal", "net_gex,IV change,gradient", "KEEP_DERIVED", "Vol expansion signal."),
    DerivationRecord("math_probabilities.py", "741", "compute_sweep_score", "tape metrics", "KEEP_DERIVED", "Sweep detection score."),
    DerivationRecord("math_probabilities.py", "796", "compute_sector_strength", "sector chg_pct", "KEEP_DERIVED", "Sector strength from context quotes."),
    DerivationRecord("math_probabilities.py", "848", "compute_iwm_confluence", "IWM confluence inputs", "KEEP_DERIVED", "IWM blended participation."),
    DerivationRecord("math_probabilities.py", "1081", "compute_volume_oi_ratio", "chains.* volume,OI", "KEEP_DERIVED", "Volume/OI per strike."),
    DerivationRecord("math_probabilities.py", "1158", "compute_option_flow_imbalance", "chains.* bidSize,askSize", "PASS_THROUGH", "Bid/ask size imbalance from Schwab leaves."),
    DerivationRecord("math_probabilities.py", "1237", "atm_flow_window_totals", "exposure buckets", "KEEP_DERIVED", "ATM window flow totals."),
    DerivationRecord("math_probabilities.py", "1300", "flow_imbalance_normalized_with_fallback", "flow totals", "KEEP_DERIVED", "Normalized flow with explicit fallback policy."),
    DerivationRecord("math_probabilities.py", "1336", "compute_smart_money_signal", "chains.* volume,OI,bid/ask size", "REPLACED", "Strike activity sums volume only when present."),
    DerivationRecord("levels.py", "22", "_fmt_level", "—", "NONE", "Level formatter."),
    DerivationRecord("levels.py", "28", "_fmt_plain_2", "—", "NONE", "Plain number formatter."),
    DerivationRecord("levels.py", "34", "to_display_rows", "ExposureRow", "NONE", "Display mapping only."),
    DerivationRecord("levels.py", "56", "walls_to_df_rows", "WallsRow", "NONE", "Walls display mapping."),
    DerivationRecord("levels.py", "91", "totals_to_df_rows", "TotalsRow", "NONE", "Totals display mapping."),
    DerivationRecord("levels.py", "118", "key_levels_to_plot_rows", "KL levels,spot", "NONE", "Plot row formatter; no derivation."),
)

SECTION4_FILES = frozenset({
    "levels.py",
    "math_exposure.py",
    "math_exposure_core.py",
    "math_levels.py",
    "math_probabilities.py",
    "math_volatility.py",
})

