"""
Section 7 Schwab-leaf derivation audit inventory (V2 decision + A2 lifecycle).

One row per ``def`` (module, class method, nested helper).
Disposition: REPLACED | KEEP_DERIVED | PASS_THROUGH | NONE
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DerivationRecord:
    file: str
    line: str
    derivation: str
    schwab_leaf: str
    disposition: str
    justification: str


SECTION7_DERIVATION_INVENTORY: tuple[DerivationRecord, ...] = (

    DerivationRecord("v2_decision/a1_conformal_artifact_attachment.py", "10", "attach_a1_conformal_artifact_to_ms_dict", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_conformal_artifact_contract.py", "18", "is_eligible_for_current_pointer", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_artifact_contract.py", "72", "is_eligible_for_current_pointer_isotonic", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_conformal_artifact_contract.py", "123", "artifact_output_path", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_artifact_contract.py", "146", "current_pointer_path", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_artifact_contract.py", "159", "_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a1_conformal_artifact_loader.py", "17", "load_a1_conformal_artifact", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "19", "derive_a1_conformal_bounds", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "57", "_honest_evaluation_passes", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "74", "_aggregate_sample_gate_passes", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "89", "_horizon_matches", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "95", "_freshness_passes", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "103", "_lineage_match_passes", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "115", "_bounded_probability_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a1_conformal_promotion.py", "122", "_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a1_isotonic_artifact_loader.py", "19", "load_a1_isotonic_artifact", "calibration artifacts", "NONE", "Calibration/artifact plumbing; no live market-field derivation."),
    DerivationRecord("v2_decision/a1_isotonic_calibration_attachment.py", "12", "attach_a1_isotonic_calibration_to_ms_dict", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_isotonic_runtime.py", "15", "apply_a1_v2_calibration_to_raw_probability", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a1_raw_probability.py", "8", "dominant_probability", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "23", "derive_et_clock_from_decision_time_ms", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "34", "is_in_rth_normal_session", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "43", "is_force_exit_clock_threshold_passed", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "52", "is_in_eod_cadence_window", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "60", "is_0dte", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "87", "_selected_chain_row", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "100", "_parse_hhmm_to_min", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "114", "_evaluate_a2_eod_force_exit_fallback", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_eod_force_exit.py", "130", "evaluate_a2_eod_force_exit", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "8", "resolve_a2_option_right", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "22", "resolve_a2_option_right_with_source", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "61", "select_a2_pin_risk_audit_row", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "90", "derive_a2_pin_risk_health", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "149", "build_a2_pin_risk_event_source", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "178", "_empty_pin_risk_health", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_health.py", "191", "_num", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "75", "build_a2_lifecycle_sidecar", "ms_dict, chain", "KEEP_DERIVED", "Lifecycle sidecar from upstream market state."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "112", "_build_event_sources", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "120", "_build_pin_risk_event_source", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "145", "_session_type", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "161", "_build_projected_preview", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "237", "_preview", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "262", "_projected_fields", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "284", "_derivation_inputs", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "350", "_input_leaf", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "364", "_schwab_leaf", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "374", "_missing_leaf", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "382", "_classified_leaf", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "390", "_has_entry_candidate", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "405", "_direction", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "415", "_mins_elapsed_since_open", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "426", "_risk", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "450", "_structural_levels", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "463", "_selected_strike", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "467", "_decision_timestamp", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "476", "_first_number", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_lifecycle_sidecar.py", "484", "_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "132", "build_a2_option_expression", "chain_row, ms_dict", "KEEP_DERIVED", "A2 OE build from Schwab-first chain row + market state."),
    DerivationRecord("v2_decision/a2_option_expression.py", "447", "_hard_gates", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "494", "_spread_exceeds_hard_threshold", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "501", "_parse_schwab_time_ms", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "513", "_quote_staleness_ms", "quotes quoteTime", "KEEP_DERIVED", "Quote staleness from Schwab time fields."),
    DerivationRecord("v2_decision/a2_option_expression.py", "543", "_soft_gates", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "565", "_late_day_gamma_health", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "609", "_leaf_value", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "620", "_handoff_mapping", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "629", "_theta", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "661", "_black_scholes_theta", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "695", "_norm_cdf", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "699", "_time_to_expiry_years", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "712", "_dte_value", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "720", "_spread_from_bid_ask", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "727", "_breakeven", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "737", "_spread_quality", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "743", "_gamma_x_oi", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "754", "_mins_to_close", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_option_expression.py", "772", "_first_number", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "780", "_num", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_option_expression.py", "789", "_clean_str", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_price_precedence.py", "8", "_num", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_price_precedence.py", "20", "contract_spread_pts_from_bid_ask", "chains.*.bid,ask", "PASS_THROUGH", "Contract spread points from Schwab bid/ask leaves only."),
    DerivationRecord("v2_decision/a2_price_precedence.py", "32", "resolve_a2_contract_mid", "chains.*.mark,bid,ask,last", "KEEP_DERIVED", "OP-006 contract mid ladder: mark → last → bid/ask/2 when mark+last absent."),
    DerivationRecord("v2_decision/a2_price_precedence.py", "54", "resolve_a2_contract_spread", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_price_precedence.py", "64", "resolve_a2_underlying_spread_pts", "ms_dict spread_pts", "PASS_THROUGH", "Underlying spread from upstream quote path; not contract spread."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "20", "build_a2_replay_label_artifact", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "47", "build_a2_replay_label", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "96", "_contract_profit_label", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "111", "_provenance", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "124", "_summary", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "136", "_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "145", "_int_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "154", "_bool_value", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "162", "_string_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_replay_labels.py", "168", "_upper_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "30", "load_a2_session_calendar", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "51", "get_session_info", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "110", "_is_valid_calendar", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "133", "_parse_hhmm_to_min", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "147", "_parse_iso_date", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "156", "_string_value", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "164", "_date_set", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/a2_session_calendar.py", "170", "_early_close_map", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "17", "build_module_a_a1_decision", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/module_a_adapter.py", "76", "_decision_block", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/module_a_adapter.py", "116", "_edge_domains", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/module_a_adapter.py", "160", "_trace_block", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/module_a_adapter.py", "176", "_direction", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "190", "_confidence", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "196", "_position_size_fraction", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "206", "_targets", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "214", "_horizon_alignment", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "234", "_first_present", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/module_a_adapter.py", "242", "_compact_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "38", "post_trade_attribution_log_path", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "43", "build_post_trade_attribution_record", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "101", "append_post_trade_attribution_record", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "111", "load_recent_post_trade_attribution_records", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "134", "_validate_post_trade_attribution_record", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "158", "_close_out_from_trade_row", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "188", "_lifecycle_from_trade_row", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "202", "_reason_code_from_trade_row", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/post_trade_attribution.py", "214", "_placeholder_block", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/schema.py", "43", "leaf", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/schema.py", "53", "validate_v2_decision", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("v2_decision/schema.py", "71", "_validate_authority", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/schema.py", "82", "_walk_leaf_fields", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("v2_decision/schema.py", "94", "_validate_leaf", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "68", "apply_time_decay", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "73", "apply_vix_adjustment", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "85", "apply_risk_multiplier", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "90", "derive_stop_distance_pct", "spot, structural levels", "KEEP_DERIVED", "Stop distance from spot and key levels."),
    DerivationRecord("lifecycle_rule_core.py", "120", "snap_target_to_structural", "upstream ms_dict / chains.*", "KEEP_DERIVED", "V2 lifecycle reads upstream Schwab-first state; no new wire ingest."),
    DerivationRecord("lifecycle_rule_core.py", "145", "derive_target_levels", "structural levels", "KEEP_DERIVED", "Target level selection from key levels geometry."),
    DerivationRecord("lifecycle_rule_core.py", "219", "resolve_same_bar_conflict", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "263", "fire_exit", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "328", "_skip", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "338", "_cap_target", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "344", "_abs_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "350", "_bar_value", "—", "NONE", "No Schwab market-field derivation in function body."),
    DerivationRecord("lifecycle_rule_core.py", "354", "_float_or_none", "—", "NONE", "No Schwab market-field derivation in function body."),
)

SECTION7_FILES = frozenset({
    "v2_decision/a1_conformal_artifact_attachment.py",
    "v2_decision/a1_conformal_artifact_contract.py",
    "v2_decision/a1_conformal_artifact_loader.py",
    "v2_decision/a1_conformal_promotion.py",
    "v2_decision/a1_isotonic_artifact_loader.py",
    "v2_decision/a1_isotonic_calibration_attachment.py",
    "v2_decision/a1_isotonic_runtime.py",
    "v2_decision/a1_raw_probability.py",
    "v2_decision/a2_eod_force_exit.py",
    "v2_decision/a2_lifecycle_health.py",
    "v2_decision/a2_lifecycle_sidecar.py",
    "v2_decision/a2_option_expression.py",
    "v2_decision/a2_price_precedence.py",
    "v2_decision/a2_replay_labels.py",
    "v2_decision/a2_session_calendar.py",
    "v2_decision/module_a_adapter.py",
    "v2_decision/post_trade_attribution.py",
    "v2_decision/schema.py",
    "lifecycle_rule_core.py",
})

